# Input linguistic variables
input_lvs = [

    {
        'X': (0, 50.1, 0.1),
        'name': 'Body Mass Index',
        'terms': {
            'low': {'umf': ('trapmf', 0, 0, 0.59, 3.95), 'lmf': ('trapmf', 0, 0, 0.09, 1.32, 1)},
            'moderately low': {'umf': ('trapmf', 0.28, 2.00, 3.00, 5.22), 'lmf': ('trapmf', 1.79, 2.37, 2.37, 2.71, 0.48)},
            'slightly low': {'umf': ('trapmf', 0.98, 2.75, 4.00, 5.41), 'lmf': ('trapmf', 2.79, 3.30, 3.30, 3.71, 0.42)},
            'healthy': {'umf': ('trapmf', 2.38, 4.50, 6.00, 8.18), 'lmf': ('trapmf', 4.79, 5.12, 5.12, 5.35, 0.27)},
            'slightly high': {'umf': ('trapmf', 4.02, 5.65, 7.00, 8.41), 'lmf': ('trapmf', 5.89, 6.34, 6.34, 6.81, 0.40)},
            'moderately high': {'umf': ('trapmf', 4.38, 6.50, 7.75, 9.62), 'lmf': ('trapmf', 6.79, 7.25, 7.25, 7.91, 0.47)},
            'high': {'umf': ('trapmf', 5.21, 8.27, 10, 10), 'lmf': ('trapmf', 7.66, 9.82, 10, 10, 1)},
        }
    },

    {
        'X': (0, 201, 1),
        'name': 'Blood Pressure',
        'terms': {
            'low': {'umf': ('trapmf', 0, 0, 0.59, 3.95), 'lmf': ('trapmf', 0, 0, 0.09, 1.32, 1)},
            'moderately low': {'umf': ('trapmf', 0.28, 2.00, 3.00, 5.22), 'lmf': ('trapmf', 1.79, 2.37, 2.37, 2.71, 0.48)},
            'slightly low': {'umf': ('trapmf', 0.98, 2.75, 4.00, 5.41), 'lmf': ('trapmf', 2.79, 3.30, 3.30, 3.71, 0.42)},
            'healthy': {'umf': ('trapmf', 2.38, 4.50, 6.00, 8.18), 'lmf': ('trapmf', 4.79, 5.12, 5.12, 5.35, 0.27)},
            'slightly high': {'umf': ('trapmf', 4.02, 5.65, 7.00, 8.41), 'lmf': ('trapmf', 5.89, 6.34, 6.34, 6.81, 0.40)},
            'moderately high': {'umf': ('trapmf', 4.38, 6.50, 7.75, 9.62), 'lmf': ('trapmf', 6.79, 7.25, 7.25, 7.91, 0.47)},
            'high': {'umf': ('trapmf', 5.21, 8.27, 10, 10), 'lmf': ('trapmf', 7.66, 9.82, 10, 10, 1)},
        }
    },

    {
        'X': (0, 201, 1),
        'name': 'Cholesterol Level',
        'terms': {
            'low': {'umf': ('trapmf', 0, 0, 0.59, 3.95), 'lmf': ('trapmf', 0, 0, 0.09, 1.32, 1)},
            'moderately low': {'umf': ('trapmf', 0.28, 2.00, 3.00, 5.22), 'lmf': ('trapmf', 1.79, 2.37, 2.37, 2.71, 0.48)},
            'slightly low': {'umf': ('trapmf', 0.98, 2.75, 4.00, 5.41), 'lmf': ('trapmf', 2.79, 3.30, 3.30, 3.71, 0.42)},
            'healthy': {'umf': ('trapmf', 2.38, 4.50, 6.00, 8.18), 'lmf': ('trapmf', 4.79, 5.12, 5.12, 5.35, 0.27)},
            'slightly high': {'umf': ('trapmf', 4.02, 5.65, 7.00, 8.41), 'lmf': ('trapmf', 5.89, 6.34, 6.34, 6.81, 0.40)},
            'moderately high': {'umf': ('trapmf', 4.38, 6.50, 7.75, 9.62), 'lmf': ('trapmf', 6.79, 7.25, 7.25, 7.91, 0.47)},
            'high': {'umf': ('trapmf', 5.21, 8.27, 10, 10), 'lmf': ('trapmf', 7.66, 9.82, 10, 10, 1)},
        }
    },

    {
        'X': (0, 2.01, 0.01),
        'name': 'Visual Acuity',
        'terms': {
            'low': {'umf': ('trapmf', 0, 0, 0.59, 3.95), 'lmf': ('trapmf', 0, 0, 0.09, 1.32, 1)},
            'moderately low': {'umf': ('trapmf', 0.28, 2.00, 3.00, 5.22), 'lmf': ('trapmf', 1.79, 2.37, 2.37, 2.71, 0.48)},
            'slightly low': {'umf': ('trapmf', 0.98, 2.75, 4.00, 5.41), 'lmf': ('trapmf', 2.79, 3.30, 3.30, 3.71, 0.42)},
            'healthy': {'umf': ('trapmf', 2.38, 4.50, 6.00, 8.18), 'lmf': ('trapmf', 4.79, 5.12, 5.12, 5.35, 0.27)},
            'slightly high': {'umf': ('trapmf', 4.02, 5.65, 7.00, 8.41), 'lmf': ('trapmf', 5.89, 6.34, 6.34, 6.81, 0.40)},
            'moderately high': {'umf': ('trapmf', 4.38, 6.50, 7.75, 9.62), 'lmf': ('trapmf', 6.79, 7.25, 7.25, 7.91, 0.47)},
            'high': {'umf': ('trapmf', 5.21, 8.27, 10, 10), 'lmf': ('trapmf', 7.66, 9.82, 10, 10, 1)},
        }
    },

    {
        'X': (0, 24.5, 0.5),
        'name': 'Sleep Duration',
        'terms': {
            'low': {'umf': ('trapmf', 0, 0, 0.59, 3.95), 'lmf': ('trapmf', 0, 0, 0.09, 1.32, 1)},
            'moderately low': {'umf': ('trapmf', 0.28, 2.00, 3.00, 5.22), 'lmf': ('trapmf', 1.79, 2.37, 2.37, 2.71, 0.48)},
            'slightly low': {'umf': ('trapmf', 0.98, 2.75, 4.00, 5.41), 'lmf': ('trapmf', 2.79, 3.30, 3.30, 3.71, 0.42)},
            'healthy': {'umf': ('trapmf', 2.38, 4.50, 6.00, 8.18), 'lmf': ('trapmf', 4.79, 5.12, 5.12, 5.35, 0.27)},
            'slightly high': {'umf': ('trapmf', 4.02, 5.65, 7.00, 8.41), 'lmf': ('trapmf', 5.89, 6.34, 6.34, 6.81, 0.40)},
            'moderately high': {'umf': ('trapmf', 4.38, 6.50, 7.75, 9.62), 'lmf': ('trapmf', 6.79, 7.25, 7.25, 7.91, 0.47)},
            'high': {'umf': ('trapmf', 5.21, 8.27, 10, 10), 'lmf': ('trapmf', 7.66, 9.82, 10, 10, 1)},
        }
    },

    {
        'X': (0, 4001, 1),
        'name': 'Cooper Test',
        'terms': {
            'low': {'umf': ('trapmf', 0, 0, 0.55, 4.61), 'lmf': ('trapmf', 0, 0, 0.09, 1.15, 1)},
            'moderately low': {'umf': ('trapmf', 0.42, 2.25, 4.00, 5.41), 'lmf': ('trapmf', 2.79, 3.21, 3.21, 0.34, 3.71)},
            'slightly low': {'umf': ('trapmf', 3.38, 5.50, 7.25, 9.02), 'lmf': ('trapmf', 5.79, 6.28, 6.28, 0.33, 6.67)},
            'healthy': {'umf': ('trapmf', 7.37, 9.36, 10, 10), 'lmf': ('trapmf', 8.68, 9.91, 10, 10, 1)},
        }
    },

    {
        'X': (0, 201, 1),
        'name': 'IQ Test',
        'terms': {
            'low': {'umf': ('trapmf', 0, 0, 0.55, 4.61), 'lmf': ('trapmf', 0, 0, 0.09, 1.15, 1)},
            'moderately low': {'umf': ('trapmf', 0.42, 2.25, 4.00, 5.41), 'lmf': ('trapmf', 2.79, 3.21, 3.21, 0.34, 3.71)},
            'slightly low': {'umf': ('trapmf', 3.38, 5.50, 7.25, 9.02), 'lmf': ('trapmf', 5.79, 6.28, 6.28, 0.33, 6.67)},
            'healthy': {'umf': ('trapmf', 7.37, 9.36, 10, 10), 'lmf': ('trapmf', 8.68, 9.91, 10, 10, 1)},
        }
    },
]

# Output linguistic variable
output_lv = {
    'X': (0, 10.1, 0.1),
    'name': 'Health Level',
    'terms': {
        'deficient': {'umf': ('trapmf', 0, 0, 0.55, 4.61), 'lmf': ('trapmf', 0, 0, 0.09, 1.15, 1)},
        'subaverage': {'umf': ('trapmf', 0.42, 2.25, 4.00, 5.41), 'lmf': ('trapmf', 2.79, 3.21, 3.21, 0.34, 3.71)},
        'average': {'umf': ('trapmf', 3.38, 5.50, 7.25, 9.02), 'lmf': ('trapmf', 5.79, 6.28, 6.28, 0.33, 6.67)},
        'excellent': {'umf': ('trapmf', 7.37, 9.36, 10, 10), 'lmf': ('trapmf', 8.68, 9.91, 10, 10, 1)},
    }
}



# Input linguistic variables
input_lvs = [

    {
        'X': (0, 50.1, 0.1),
        'name': 'Body Mass Index',
        'terms': {
            'low': {'umf': ('trapmf', 0, 0, 0.59, 3.95), 'lmf': ('trapmf', 0, 0, 0.09, 1.32, 1)},
            'moderately low': {'umf': ('trapmf', 0.28, 2.00, 3.00, 5.22), 'lmf': ('trapmf', 1.79, 2.37, 2.37, 2.71, 0.48)},
            'slightly low': {'umf': ('trapmf', 0.98, 2.75, 4.00, 5.41), 'lmf': ('trapmf', 2.79, 3.30, 3.30, 3.71, 0.42)},
            'healthy': {'umf': ('trapmf', 2.38, 4.50, 6.00, 8.18), 'lmf': ('trapmf', 4.79, 5.12, 5.12, 5.35, 0.27)},
            'slightly high': {'umf': ('trapmf', 4.02, 5.65, 7.00, 8.41), 'lmf': ('trapmf', 5.89, 6.34, 6.34, 6.81, 0.40)},
            'moderately high': {'umf': ('trapmf', 4.38, 6.50, 7.75, 9.62), 'lmf': ('trapmf', 6.79, 7.25, 7.25, 7.91, 0.47)},
            'high': {'umf': ('trapmf', 5.21, 8.27, 10, 10), 'lmf': ('trapmf', 7.66, 9.82, 10, 10, 1)},
        }
    },

    {
        'X': (0, 201, 1),
        'name': 'Blood Pressure',
        'terms': {
            'low': {'umf': ('trapmf', 0, 0, 0.59, 3.95), 'lmf': ('trapmf', 0, 0, 0.09, 1.32, 1)},
            'moderately low': {'umf': ('trapmf', 0.28, 2.00, 3.00, 5.22), 'lmf': ('trapmf', 1.79, 2.37, 2.37, 2.71, 0.48)},
            'slightly low': {'umf': ('trapmf', 0.98, 2.75, 4.00, 5.41), 'lmf': ('trapmf', 2.79, 3.30, 3.30, 3.71, 0.42)},
            'healthy': {'umf': ('trapmf', 2.38, 4.50, 6.00, 8.18), 'lmf': ('trapmf', 4.79, 5.12, 5.12, 5.35, 0.27)},
            'slightly high': {'umf': ('trapmf', 4.02, 5.65, 7.00, 8.41), 'lmf': ('trapmf', 5.89, 6.34, 6.34, 6.81, 0.40)},
            'moderately high': {'umf': ('trapmf', 4.38, 6.50, 7.75, 9.62), 'lmf': ('trapmf', 6.79, 7.25, 7.25, 7.91, 0.47)},
            'high': {'umf': ('trapmf', 5.21, 8.27, 10, 10), 'lmf': ('trapmf', 7.66, 9.82, 10, 10, 1)},
        }
    },

    {
        'X': (0, 201, 1),
        'name': 'Cholesterol Level',
        'terms': {
            'low': {'umf': ('trapmf', 0, 0, 0.59, 3.95), 'lmf': ('trapmf', 0, 0, 0.09, 1.32, 1)},
            'moderately low': {'umf': ('trapmf', 0.28, 2.00, 3.00, 5.22), 'lmf': ('trapmf', 1.79, 2.37, 2.37, 2.71, 0.48)},
            'slightly low': {'umf': ('trapmf', 0.98, 2.75, 4.00, 5.41), 'lmf': ('trapmf', 2.79, 3.30, 3.30, 3.71, 0.42)},
            'healthy': {'umf': ('trapmf', 2.38, 4.50, 6.00, 8.18), 'lmf': ('trapmf', 4.79, 5.12, 5.12, 5.35, 0.27)},
            'slightly high': {'umf': ('trapmf', 4.02, 5.65, 7.00, 8.41), 'lmf': ('trapmf', 5.89, 6.34, 6.34, 6.81, 0.40)},
            'moderately high': {'umf': ('trapmf', 4.38, 6.50, 7.75, 9.62), 'lmf': ('trapmf', 6.79, 7.25, 7.25, 7.91, 0.47)},
            'high': {'umf': ('trapmf', 5.21, 8.27, 10, 10), 'lmf': ('trapmf', 7.66, 9.82, 10, 10, 1)},
        }
    },

    {
        'X': (0, 2.01, 0.01),
        'name': 'Visual Acuity',
        'terms': {
            'low': {'umf': ('trapmf', 0, 0, 0.59, 3.95), 'lmf': ('trapmf', 0, 0, 0.09, 1.32, 1)},
            'moderately low': {'umf': ('trapmf', 0.28, 2.00, 3.00, 5.22), 'lmf': ('trapmf', 1.79, 2.37, 2.37, 2.71, 0.48)},
            'slightly low': {'umf': ('trapmf', 0.98, 2.75, 4.00, 5.41), 'lmf': ('trapmf', 2.79, 3.30, 3.30, 3.71, 0.42)},
            'healthy': {'umf': ('trapmf', 2.38, 4.50, 6.00, 8.18), 'lmf': ('trapmf', 4.79, 5.12, 5.12, 5.35, 0.27)},
            'slightly high': {'umf': ('trapmf', 4.02, 5.65, 7.00, 8.41), 'lmf': ('trapmf', 5.89, 6.34, 6.34, 6.81, 0.40)},
            'moderately high': {'umf': ('trapmf', 4.38, 6.50, 7.75, 9.62), 'lmf': ('trapmf', 6.79, 7.25, 7.25, 7.91, 0.47)},
            'high': {'umf': ('trapmf', 5.21, 8.27, 10, 10), 'lmf': ('trapmf', 7.66, 9.82, 10, 10, 1)},
        }
    },

    {
        'X': (0, 24.5, 0.5),
        'name': 'Sleep Duration',
        'terms': {
            'low': {'umf': ('trapmf', 0, 0, 0.59, 3.95), 'lmf': ('trapmf', 0, 0, 0.09, 1.32, 1)},
            'moderately low': {'umf': ('trapmf', 0.28, 2.00, 3.00, 5.22), 'lmf': ('trapmf', 1.79, 2.37, 2.37, 2.71, 0.48)},
            'slightly low': {'umf': ('trapmf', 0.98, 2.75, 4.00, 5.41), 'lmf': ('trapmf', 2.79, 3.30, 3.30, 3.71, 0.42)},
            'healthy': {'umf': ('trapmf', 2.38, 4.50, 6.00, 8.18), 'lmf': ('trapmf', 4.79, 5.12, 5.12, 5.35, 0.27)},
            'slightly high': {'umf': ('trapmf', 4.02, 5.65, 7.00, 8.41), 'lmf': ('trapmf', 5.89, 6.34, 6.34, 6.81, 0.40)},
            'moderately high': {'umf': ('trapmf', 4.38, 6.50, 7.75, 9.62), 'lmf': ('trapmf', 6.79, 7.25, 7.25, 7.91, 0.47)},
            'high': {'umf': ('trapmf', 5.21, 8.27, 10, 10), 'lmf': ('trapmf', 7.66, 9.82, 10, 10, 1)},
        }
    },

    {
        'X': (0, 4001, 1),
        'name': 'Cooper Test',
        'terms': {
            'low': {'umf': ('trapmf', 0, 0, 0.55, 4.61), 'lmf': ('trapmf', 0, 0, 0.09, 1.15, 1)},
            'moderately low': {'umf': ('trapmf', 0.42, 2.25, 4.00, 5.41), 'lmf': ('trapmf', 2.79, 3.21, 3.21, 0.34, 3.71)},
            'slightly low': {'umf': ('trapmf', 3.38, 5.50, 7.25, 9.02), 'lmf': ('trapmf', 5.79, 6.28, 6.28, 0.33, 6.67)},
            'healthy': {'umf': ('trapmf', 7.37, 9.36, 10, 10), 'lmf': ('trapmf', 8.68, 9.91, 10, 10, 1)},
        }
    },

    {
        'X': (0, 201, 1),
        'name': 'IQ Test',
        'terms': {
            'low': {'umf': ('trapmf', 0, 0, 0.55, 4.61), 'lmf': ('trapmf', 0, 0, 0.09, 1.15, 1)},
            'moderately low': {'umf': ('trapmf', 0.42, 2.25, 4.00, 5.41), 'lmf': ('trapmf', 2.79, 3.21, 3.21, 0.34, 3.71)},
            'slightly low': {'umf': ('trapmf', 3.38, 5.50, 7.25, 9.02), 'lmf': ('trapmf', 5.79, 6.28, 6.28, 0.33, 6.67)},
            'healthy': {'umf': ('trapmf', 7.37, 9.36, 10, 10), 'lmf': ('trapmf', 8.68, 9.91, 10, 10, 1)},
        }
    },
]

# Output linguistic variable
output_lv = {
    'X': (0, 10.1, 0.1),
    'name': 'Health Level',
    'terms': {
        'deficient': {'umf': ('trapmf', 0, 0, 0.55, 4.61), 'lmf': ('trapmf', 0, 0, 0.09, 1.15, 1)},
        'subaverage': {'umf': ('trapmf', 0.42, 2.25, 4.00, 5.41), 'lmf': ('trapmf', 2.79, 3.21, 3.21, 0.34, 3.71)},
        'average': {'umf': ('trapmf', 3.38, 5.50, 7.25, 9.02), 'lmf': ('trapmf', 5.79, 6.28, 6.28, 0.33, 6.67)},
        'excellent': {'umf': ('trapmf', 7.37, 9.36, 10, 10), 'lmf': ('trapmf', 8.68, 9.91, 10, 10, 1)},
    }
}


# Knowledge base of rules
rule_base = [
    
    (('low', 'low', 'low', 'low', 'low', 'low', 'low'), 'deficient'),
    (('low', 'low', 'low', 'low', 'low', 'low', 'healthy'), 'deficient'),
    (('low', 'low', 'low', 'low', 'low', 'healthy', 'low'), 'deficient'),
    (('low', 'low', 'low', 'low', 'low', 'healthy', 'healthy'), 'deficient'),
    (('low', 'low', 'low', 'low', 'healthy', 'low', 'low'), 'deficient'),
    (('low', 'low', 'low', 'low', 'healthy', 'low', 'healthy'), 'deficient'),
    (('low', 'low', 'low', 'low', 'healthy', 'healthy', 'low'), 'deficient'),
    (('low', 'low', 'low', 'low', 'healthy', 'healthy', 'healthy'), 'average'),
    (('low', 'low', 'low', 'low', 'high', 'low', 'low'), 'deficient'),
    (('low', 'low', 'low', 'low', 'high', 'low', 'healthy'), 'deficient'),
    (('low', 'low', 'low', 'low', 'high', 'healthy', 'low'), 'deficient'),
    (('low', 'low', 'low', 'low', 'high', 'healthy', 'healthy'), 'deficient'),
    (('low', 'low', 'low', 'healthy', 'low', 'low', 'low'), 'deficient'),
    (('low', 'low', 'low', 'healthy', 'low', 'low', 'healthy'), 'deficient'),
    (('low', 'low', 'low', 'healthy', 'low', 'healthy', 'low'), 'deficient'),
    (('low', 'low', 'low', 'healthy', 'low', 'healthy', 'healthy'), 'deficient'),
    (('low', 'low', 'low', 'healthy', 'healthy', 'low', 'low'), 'deficient'),
    (('low', 'low', 'low', 'healthy', 'healthy', 'low', 'healthy'), 'deficient'),
    (('low', 'low', 'low', 'healthy', 'healthy', 'healthy', 'low'), 'average'),
    (('low', 'low', 'low', 'healthy', 'healthy', 'healthy', 'healthy'), 'average'),
    (('low', 'low', 'low', 'healthy', 'high', 'low', 'low'), 'deficient'),
    (('low', 'low', 'low', 'healthy', 'high', 'low', 'healthy'), 'deficient'),
    (('low', 'low', 'low', 'healthy', 'high', 'healthy', 'low'), 'deficient'),
    (('low', 'low', 'low', 'healthy', 'high', 'healthy', 'healthy'), 'deficient'),
    (('low', 'low', 'low', 'high', 'low', 'low', 'low'), 'deficient'),
    (('low', 'low', 'low', 'high', 'low', 'low', 'healthy'), 'deficient'),
    (('low', 'low', 'low', 'high', 'low', 'healthy', 'low'), 'deficient'),
    (('low', 'low', 'low', 'high', 'low', 'healthy', 'healthy'), 'deficient'),
    (('low', 'low', 'low', 'high', 'healthy', 'low', 'low'), 'deficient'),
    (('low', 'low', 'low', 'high', 'healthy', 'low', 'healthy'), 'deficient'),
    (('low', 'low', 'low', 'high', 'healthy', 'healthy', 'low'), 'deficient'),
    (('low', 'low', 'low', 'high', 'healthy', 'healthy', 'healthy'), 'average'),
    (('low', 'low', 'low', 'high', 'high', 'low', 'low'), 'deficient'),
    (('low', 'low', 'low', 'high', 'high', 'low', 'healthy'), 'deficient'),
    (('low', 'low', 'low', 'high', 'high', 'healthy', 'low'), 'deficient'),
    (('low', 'low', 'low', 'high', 'high', 'healthy', 'healthy'), 'deficient'),
    (('low', 'low', 'healthy', 'low', 'low', 'low', 'low'), 'deficient'),
    (('low', 'low', 'healthy', 'low', 'low', 'low', 'healthy'), 'deficient'),
    (('low', 'low', 'healthy', 'low', 'low', 'healthy', 'low'), 'deficient'),
    (('low', 'low', 'healthy', 'low', 'low', 'healthy', 'healthy'), 'average'),
    (('low', 'low', 'healthy', 'low', 'healthy', 'low', 'low'), 'average'),
    (('low', 'low', 'healthy', 'low', 'healthy', 'low', 'healthy'), 'average'),
    (('low', 'low', 'healthy', 'low', 'healthy', 'healthy', 'low'), 'average'),
    (('low', 'low', 'healthy', 'low', 'healthy', 'healthy', 'healthy'), 'average'),
    (('low', 'low', 'healthy', 'low', 'high', 'low', 'low'), 'deficient'),
    (('low', 'low', 'healthy', 'low', 'high', 'low', 'healthy'), 'deficient'),
    (('low', 'low', 'healthy', 'low', 'high', 'healthy', 'low'), 'deficient'),
    (('low', 'low', 'healthy', 'low', 'high', 'healthy', 'healthy'), 'average'),
    (('low', 'low', 'healthy', 'healthy', 'low', 'low', 'low'), 'deficient'),
    (('low', 'low', 'healthy', 'healthy', 'low', 'low', 'healthy'), 'deficient'),
    (('low', 'low', 'healthy', 'healthy', 'low', 'healthy', 'low'), 'average'),
    (('low', 'low', 'healthy', 'healthy', 'low', 'healthy', 'healthy'), 'average'),
    (('low', 'low', 'healthy', 'healthy', 'healthy', 'low', 'low'), 'average'),
    (('low', 'low', 'healthy', 'healthy', 'healthy', 'low', 'healthy'), 'average'),
    (('low', 'low', 'healthy', 'healthy', 'healthy', 'healthy', 'low'), 'average'),
    (('low', 'low', 'healthy', 'healthy', 'healthy', 'healthy', 'healthy'), 'average'),
    (('low', 'low', 'healthy', 'healthy', 'high', 'low', 'low'), 'deficient'),
    (('low', 'low', 'healthy', 'healthy', 'high', 'low', 'healthy'), 'deficient'),
    (('low', 'low', 'healthy', 'healthy', 'high', 'healthy', 'low'), 'average'),
    (('low', 'low', 'healthy', 'healthy', 'high', 'healthy', 'healthy'), 'average'),
    (('low', 'low', 'healthy', 'high', 'low', 'low', 'low'), 'deficient'),
    (('low', 'low', 'healthy', 'high', 'low', 'low', 'healthy'), 'deficient'),
    (('low', 'low', 'healthy', 'high', 'low', 'healthy', 'low'), 'deficient'),
    (('low', 'low', 'healthy', 'high', 'low', 'healthy', 'healthy'), 'average'),
    (('low', 'low', 'healthy', 'high', 'healthy', 'low', 'low'), 'average'),
    (('low', 'low', 'healthy', 'high', 'healthy', 'low', 'healthy'), 'average'),
    (('low', 'low', 'healthy', 'high', 'healthy', 'healthy', 'low'), 'average'),
    (('low', 'low', 'healthy', 'high', 'healthy', 'healthy', 'healthy'), 'average'),
    (('low', 'low', 'healthy', 'high', 'high', 'low', 'low'), 'deficient'),
    (('low', 'low', 'healthy', 'high', 'high', 'low', 'healthy'), 'deficient'),
    (('low', 'low', 'healthy', 'high', 'high', 'healthy', 'low'), 'deficient'),
    (('low', 'low', 'healthy', 'high', 'high', 'healthy', 'healthy'), 'average'),
    (('low', 'low', 'high', 'low', 'low', 'low', 'low'), 'deficient'),
    (('low', 'low', 'high', 'low', 'low', 'low', 'healthy'), 'deficient'),
    (('low', 'low', 'high', 'low', 'low', 'healthy', 'low'), 'deficient'),
    (('low', 'low', 'high', 'low', 'low', 'healthy', 'healthy'), 'deficient'),
    (('low', 'low', 'high', 'low', 'healthy', 'low', 'low'), 'deficient'),
    (('low', 'low', 'high', 'low', 'healthy', 'low', 'healthy'), 'deficient'),
    (('low', 'low', 'high', 'low', 'healthy', 'healthy', 'low'), 'deficient'),
    (('low', 'low', 'high', 'low', 'healthy', 'healthy', 'healthy'), 'average'),
    (('low', 'low', 'high', 'low', 'high', 'low', 'low'), 'deficient'),
    (('low', 'low', 'high', 'low', 'high', 'low', 'healthy'), 'deficient'),
    (('low', 'low', 'high', 'low', 'high', 'healthy', 'low'), 'deficient'),
    (('low', 'low', 'high', 'low', 'high', 'healthy', 'healthy'), 'deficient'),
    (('low', 'low', 'high', 'healthy', 'low', 'low', 'low'), 'deficient'),
    (('low', 'low', 'high', 'healthy', 'low', 'low', 'healthy'), 'deficient'),
    (('low', 'low', 'high', 'healthy', 'low', 'healthy', 'low'), 'deficient'),
    (('low', 'low', 'high', 'healthy', 'low', 'healthy', 'healthy'), 'deficient'),
    (('low', 'low', 'high', 'healthy', 'healthy', 'low', 'low'), 'deficient'),
    (('low', 'low', 'high', 'healthy', 'healthy', 'low', 'healthy'), 'deficient'),
    (('low', 'low', 'high', 'healthy', 'healthy', 'healthy', 'low'), 'average'),
    (('low', 'low', 'high', 'healthy', 'healthy', 'healthy', 'healthy'), 'average'),
    (('low', 'low', 'high', 'healthy', 'high', 'low', 'low'), 'deficient'),
    (('low', 'low', 'high', 'healthy', 'high', 'low', 'healthy'), 'deficient'),
    (('low', 'low', 'high', 'healthy', 'high', 'healthy', 'low'), 'deficient'),
    (('low', 'low', 'high', 'healthy', 'high', 'healthy', 'healthy'), 'deficient'),
    (('low', 'low', 'high', 'high', 'low', 'low', 'low'), 'deficient'),
    (('low', 'low', 'high', 'high', 'low', 'low', 'healthy'), 'deficient'),
    (('low', 'low', 'high', 'high', 'low', 'healthy', 'low'), 'deficient'),
    (('low', 'low', 'high', 'high', 'low', 'healthy', 'healthy'), 'deficient'),
    (('low', 'low', 'high', 'high', 'healthy', 'low', 'low'), 'deficient'),
    (('low', 'low', 'high', 'high', 'healthy', 'low', 'healthy'), 'deficient'),
    (('low', 'low', 'high', 'high', 'healthy', 'healthy', 'low'), 'deficient'),
    (('low', 'low', 'high', 'high', 'healthy', 'healthy', 'healthy'), 'average'),
    (('low', 'low', 'high', 'high', 'high', 'low', 'low'), 'deficient'),
    (('low', 'low', 'high', 'high', 'high', 'low', 'healthy'), 'deficient'),
    (('low', 'low', 'high', 'high', 'high', 'healthy', 'low'), 'deficient'),
    (('low', 'low', 'high', 'high', 'high', 'healthy', 'healthy'), 'deficient'),
    (('low', 'healthy', 'low', 'low', 'low', 'low', 'low'), 'deficient'),
    (('low', 'healthy', 'low', 'low', 'low', 'low', 'healthy'), 'deficient'),
    (('low', 'healthy', 'low', 'low', 'low', 'healthy', 'low'), 'average'),
    (('low', 'healthy', 'low', 'low', 'low', 'healthy', 'healthy'), 'average'),
    (('low', 'healthy', 'low', 'low', 'healthy', 'low', 'low'), 'average'),
    (('low', 'healthy', 'low', 'low', 'healthy', 'low', 'healthy'), 'average'),
    (('low', 'healthy', 'low', 'low', 'healthy', 'healthy', 'low'), 'average'),
    (('low', 'healthy', 'low', 'low', 'healthy', 'healthy', 'healthy'), 'average'),
    (('low', 'healthy', 'low', 'low', 'high', 'low', 'low'), 'deficient'),
    (('low', 'healthy', 'low', 'low', 'high', 'low', 'healthy'), 'deficient'),
    (('low', 'healthy', 'low', 'low', 'high', 'healthy', 'low'), 'average'),
    (('low', 'healthy', 'low', 'low', 'high', 'healthy', 'healthy'), 'average'),
    (('low', 'healthy', 'low', 'healthy', 'low', 'low', 'low'), 'deficient'),
    (('low', 'healthy', 'low', 'healthy', 'low', 'low', 'healthy'), 'average'),
    (('low', 'healthy', 'low', 'healthy', 'low', 'healthy', 'low'), 'average'),
    (('low', 'healthy', 'low', 'healthy', 'low', 'healthy', 'healthy'), 'average'),
    (('low', 'healthy', 'low', 'healthy', 'healthy', 'low', 'low'), 'average'),
    (('low', 'healthy', 'low', 'healthy', 'healthy', 'low', 'healthy'), 'average'),
    (('low', 'healthy', 'low', 'healthy', 'healthy', 'healthy', 'low'), 'average'),
    (('low', 'healthy', 'low', 'healthy', 'healthy', 'healthy', 'healthy'), 'average'),
    (('low', 'healthy', 'low', 'healthy', 'high', 'low', 'low'), 'deficient'),
    (('low', 'healthy', 'low', 'healthy', 'high', 'low', 'healthy'), 'average'),
    (('low', 'healthy', 'low', 'healthy', 'high', 'healthy', 'low'), 'average'),
    (('low', 'healthy', 'low', 'healthy', 'high', 'healthy', 'healthy'), 'average'),
    (('low', 'healthy', 'low', 'high', 'low', 'low', 'low'), 'deficient'),
    (('low', 'healthy', 'low', 'high', 'low', 'low', 'healthy'), 'deficient'),
    (('low', 'healthy', 'low', 'high', 'low', 'healthy', 'low'), 'average'),
    (('low', 'healthy', 'low', 'high', 'low', 'healthy', 'healthy'), 'average'),
    (('low', 'healthy', 'low', 'high', 'healthy', 'low', 'low'), 'average'),
    (('low', 'healthy', 'low', 'high', 'healthy', 'low', 'healthy'), 'average'),
    (('low', 'healthy', 'low', 'high', 'healthy', 'healthy', 'low'), 'average'),
    (('low', 'healthy', 'low', 'high', 'healthy', 'healthy', 'healthy'), 'average'),
    (('low', 'healthy', 'low', 'high', 'high', 'low', 'low'), 'deficient'),
    (('low', 'healthy', 'low', 'high', 'high', 'low', 'healthy'), 'deficient'),
    (('low', 'healthy', 'low', 'high', 'high', 'healthy', 'low'), 'average'),
    (('low', 'healthy', 'low', 'high', 'high', 'healthy', 'healthy'), 'average'),
    (('low', 'healthy', 'healthy', 'low', 'low', 'low', 'low'), 'average'),
    (('low', 'healthy', 'healthy', 'low', 'low', 'low', 'healthy'), 'average'),
    (('low', 'healthy', 'healthy', 'low', 'low', 'healthy', 'low'), 'average'),
    (('low', 'healthy', 'healthy', 'low', 'low', 'healthy', 'healthy'), 'average'),
    (('low', 'healthy', 'healthy', 'low', 'healthy', 'low', 'low'), 'average'),
    (('low', 'healthy', 'healthy', 'low', 'healthy', 'low', 'healthy'), 'average'),
    (('low', 'healthy', 'healthy', 'low', 'healthy', 'healthy', 'low'), 'average'),
    (('low', 'healthy', 'healthy', 'low', 'healthy', 'healthy', 'healthy'), 'average'),
    (('low', 'healthy', 'healthy', 'low', 'high', 'low', 'low'), 'average'),
    (('low', 'healthy', 'healthy', 'low', 'high', 'low', 'healthy'), 'average'),
    (('low', 'healthy', 'healthy', 'low', 'high', 'healthy', 'low'), 'average'),
    (('low', 'healthy', 'healthy', 'low', 'high', 'healthy', 'healthy'), 'average'),
    (('low', 'healthy', 'healthy', 'healthy', 'low', 'low', 'low'), 'average'),
    (('low', 'healthy', 'healthy', 'healthy', 'low', 'low', 'healthy'), 'average'),
    (('low', 'healthy', 'healthy', 'healthy', 'low', 'healthy', 'low'), 'average'),
    (('low', 'healthy', 'healthy', 'healthy', 'low', 'healthy', 'healthy'), 'average'),
    (('low', 'healthy', 'healthy', 'healthy', 'healthy', 'low', 'low'), 'average'),
    (('low', 'healthy', 'healthy', 'healthy', 'healthy', 'low', 'healthy'), 'average'),
    (('low', 'healthy', 'healthy', 'healthy', 'healthy', 'healthy', 'low'), 'average'),
    (('low', 'healthy', 'healthy', 'healthy', 'healthy', 'healthy', 'healthy'), 'average'),
    (('low', 'healthy', 'healthy', 'healthy', 'high', 'low', 'low'), 'average'),
    (('low', 'healthy', 'healthy', 'healthy', 'high', 'low', 'healthy'), 'average'),
    (('low', 'healthy', 'healthy', 'healthy', 'high', 'healthy', 'low'), 'average'),
    (('low', 'healthy', 'healthy', 'healthy', 'high', 'healthy', 'healthy'), 'average'),
    (('low', 'healthy', 'healthy', 'high', 'low', 'low', 'low'), 'average'),
    (('low', 'healthy', 'healthy', 'high', 'low', 'low', 'healthy'), 'average'),
    (('low', 'healthy', 'healthy', 'high', 'low', 'healthy', 'low'), 'average'),
    (('low', 'healthy', 'healthy', 'high', 'low', 'healthy', 'healthy'), 'average'),
    (('low', 'healthy', 'healthy', 'high', 'healthy', 'low', 'low'), 'average'),
    (('low', 'healthy', 'healthy', 'high', 'healthy', 'low', 'healthy'), 'average'),
    (('low', 'healthy', 'healthy', 'high', 'healthy', 'healthy', 'low'), 'average'),
    (('low', 'healthy', 'healthy', 'high', 'healthy', 'healthy', 'healthy'), 'average'),
    (('low', 'healthy', 'healthy', 'high', 'high', 'low', 'low'), 'average'),
    (('low', 'healthy', 'healthy', 'high', 'high', 'low', 'healthy'), 'average'),
    (('low', 'healthy', 'healthy', 'high', 'high', 'healthy', 'low'), 'average'),
    (('low', 'healthy', 'healthy', 'high', 'high', 'healthy', 'healthy'), 'average'),
    (('low', 'healthy', 'high', 'low', 'low', 'low', 'low'), 'deficient'),
    (('low', 'healthy', 'high', 'low', 'low', 'low', 'healthy'), 'deficient'),
    (('low', 'healthy', 'high', 'low', 'low', 'healthy', 'low'), 'average'),
    (('low', 'healthy', 'high', 'low', 'low', 'healthy', 'healthy'), 'average'),
    (('low', 'healthy', 'high', 'low', 'healthy', 'low', 'low'), 'average'),
    (('low', 'healthy', 'high', 'low', 'healthy', 'low', 'healthy'), 'average'),
    (('low', 'healthy', 'high', 'low', 'healthy', 'healthy', 'low'), 'average'),
    (('low', 'healthy', 'high', 'low', 'healthy', 'healthy', 'healthy'), 'average'),
    (('low', 'healthy', 'high', 'low', 'high', 'low', 'low'), 'deficient'),
    (('low', 'healthy', 'high', 'low', 'high', 'low', 'healthy'), 'deficient'),
    (('low', 'healthy', 'high', 'low', 'high', 'healthy', 'low'), 'average'),
    (('low', 'healthy', 'high', 'low', 'high', 'healthy', 'healthy'), 'average'),
    (('low', 'healthy', 'high', 'healthy', 'low', 'low', 'low'), 'deficient'),
    (('low', 'healthy', 'high', 'healthy', 'low', 'low', 'healthy'), 'average'),
    (('low', 'healthy', 'high', 'healthy', 'low', 'healthy', 'low'), 'average'),
    (('low', 'healthy', 'high', 'healthy', 'low', 'healthy', 'healthy'), 'average'),
    (('low', 'healthy', 'high', 'healthy', 'healthy', 'low', 'low'), 'average'),
    (('low', 'healthy', 'high', 'healthy', 'healthy', 'low', 'healthy'), 'average'),
    (('low', 'healthy', 'high', 'healthy', 'healthy', 'healthy', 'low'), 'average'),
    (('low', 'healthy', 'high', 'healthy', 'healthy', 'healthy', 'healthy'), 'average'),
    (('low', 'healthy', 'high', 'healthy', 'high', 'low', 'low'), 'deficient'),
    (('low', 'healthy', 'high', 'healthy', 'high', 'low', 'healthy'), 'average'),
    (('low', 'healthy', 'high', 'healthy', 'high', 'healthy', 'low'), 'average'),
    (('low', 'healthy', 'high', 'healthy', 'high', 'healthy', 'healthy'), 'average'),
    (('low', 'healthy', 'high', 'high', 'low', 'low', 'low'), 'deficient'),
    (('low', 'healthy', 'high', 'high', 'low', 'low', 'healthy'), 'deficient'),
    (('low', 'healthy', 'high', 'high', 'low', 'healthy', 'low'), 'average'),
    (('low', 'healthy', 'high', 'high', 'low', 'healthy', 'healthy'), 'average'),
    (('low', 'healthy', 'high', 'high', 'healthy', 'low', 'low'), 'average'),
    (('low', 'healthy', 'high', 'high', 'healthy', 'low', 'healthy'), 'average'),
    (('low', 'healthy', 'high', 'high', 'healthy', 'healthy', 'low'), 'average'),
    (('low', 'healthy', 'high', 'high', 'healthy', 'healthy', 'healthy'), 'average'),
    (('low', 'healthy', 'high', 'high', 'high', 'low', 'low'), 'deficient'),
    (('low', 'healthy', 'high', 'high', 'high', 'low', 'healthy'), 'deficient'),
    (('low', 'healthy', 'high', 'high', 'high', 'healthy', 'low'), 'average'),
    (('low', 'healthy', 'high', 'high', 'high', 'healthy', 'healthy'), 'average'),
    (('low', 'high', 'low', 'low', 'low', 'low', 'low'), 'deficient'),
    (('low', 'high', 'low', 'low', 'low', 'low', 'healthy'), 'deficient'),
    (('low', 'high', 'low', 'low', 'low', 'healthy', 'low'), 'deficient'),
    (('low', 'high', 'low', 'low', 'low', 'healthy', 'healthy'), 'deficient'),
    (('low', 'high', 'low', 'low', 'healthy', 'low', 'low'), 'deficient'),
    (('low', 'high', 'low', 'low', 'healthy', 'low', 'healthy'), 'deficient'),
    (('low', 'high', 'low', 'low', 'healthy', 'healthy', 'low'), 'deficient'),
    (('low', 'high', 'low', 'low', 'healthy', 'healthy', 'healthy'), 'average'),
    (('low', 'high', 'low', 'low', 'high', 'low', 'low'), 'deficient'),
    (('low', 'high', 'low', 'low', 'high', 'low', 'healthy'), 'deficient'),
    (('low', 'high', 'low', 'low', 'high', 'healthy', 'low'), 'deficient'),
    (('low', 'high', 'low', 'low', 'high', 'healthy', 'healthy'), 'deficient'),
    (('low', 'high', 'low', 'healthy', 'low', 'low', 'low'), 'deficient'),
    (('low', 'high', 'low', 'healthy', 'low', 'low', 'healthy'), 'deficient'),
    (('low', 'high', 'low', 'healthy', 'low', 'healthy', 'low'), 'deficient'),
    (('low', 'high', 'low', 'healthy', 'low', 'healthy', 'healthy'), 'deficient'),
    (('low', 'high', 'low', 'healthy', 'healthy', 'low', 'low'), 'deficient'),
    (('low', 'high', 'low', 'healthy', 'healthy', 'low', 'healthy'), 'deficient'),
    (('low', 'high', 'low', 'healthy', 'healthy', 'healthy', 'low'), 'average'),
    (('low', 'high', 'low', 'healthy', 'healthy', 'healthy', 'healthy'), 'average'),
    (('low', 'high', 'low', 'healthy', 'high', 'low', 'low'), 'deficient'),
    (('low', 'high', 'low', 'healthy', 'high', 'low', 'healthy'), 'deficient'),
    (('low', 'high', 'low', 'healthy', 'high', 'healthy', 'low'), 'deficient'),
    (('low', 'high', 'low', 'healthy', 'high', 'healthy', 'healthy'), 'deficient'),
    (('low', 'high', 'low', 'high', 'low', 'low', 'low'), 'deficient'),
    (('low', 'high', 'low', 'high', 'low', 'low', 'healthy'), 'deficient'),
    (('low', 'high', 'low', 'high', 'low', 'healthy', 'low'), 'deficient'),
    (('low', 'high', 'low', 'high', 'low', 'healthy', 'healthy'), 'deficient'),
    (('low', 'high', 'low', 'high', 'healthy', 'low', 'low'), 'deficient'),
    (('low', 'high', 'low', 'high', 'healthy', 'low', 'healthy'), 'deficient'),
    (('low', 'high', 'low', 'high', 'healthy', 'healthy', 'low'), 'deficient'),
    (('low', 'high', 'low', 'high', 'healthy', 'healthy', 'healthy'), 'average'),
    (('low', 'high', 'low', 'high', 'high', 'low', 'low'), 'deficient'),
    (('low', 'high', 'low', 'high', 'high', 'low', 'healthy'), 'deficient'),
    (('low', 'high', 'low', 'high', 'high', 'healthy', 'low'), 'deficient'),
    (('low', 'high', 'low', 'high', 'high', 'healthy', 'healthy'), 'deficient'),
    (('low', 'high', 'healthy', 'low', 'low', 'low', 'low'), 'deficient'),
    (('low', 'high', 'healthy', 'low', 'low', 'low', 'healthy'), 'deficient'),
    (('low', 'high', 'healthy', 'low', 'low', 'healthy', 'low'), 'deficient'),
    (('low', 'high', 'healthy', 'low', 'low', 'healthy', 'healthy'), 'average'),
    (('low', 'high', 'healthy', 'low', 'healthy', 'low', 'low'), 'average'),
    (('low', 'high', 'healthy', 'low', 'healthy', 'low', 'healthy'), 'average'),
    (('low', 'high', 'healthy', 'low', 'healthy', 'healthy', 'low'), 'average'),
    (('low', 'high', 'healthy', 'low', 'healthy', 'healthy', 'healthy'), 'average'),
    (('low', 'high', 'healthy', 'low', 'high', 'low', 'low'), 'deficient'),
    (('low', 'high', 'healthy', 'low', 'high', 'low', 'healthy'), 'deficient'),
    (('low', 'high', 'healthy', 'low', 'high', 'healthy', 'low'), 'deficient'),
    (('low', 'high', 'healthy', 'low', 'high', 'healthy', 'healthy'), 'average'),
    (('low', 'high', 'healthy', 'healthy', 'low', 'low', 'low'), 'deficient'),
    (('low', 'high', 'healthy', 'healthy', 'low', 'low', 'healthy'), 'deficient'),
    (('low', 'high', 'healthy', 'healthy', 'low', 'healthy', 'low'), 'average'),
    (('low', 'high', 'healthy', 'healthy', 'low', 'healthy', 'healthy'), 'average'),
    (('low', 'high', 'healthy', 'healthy', 'healthy', 'low', 'low'), 'average'),
    (('low', 'high', 'healthy', 'healthy', 'healthy', 'low', 'healthy'), 'average'),
    (('low', 'high', 'healthy', 'healthy', 'healthy', 'healthy', 'low'), 'average'),
    (('low', 'high', 'healthy', 'healthy', 'healthy', 'healthy', 'healthy'), 'average'),
    (('low', 'high', 'healthy', 'healthy', 'high', 'low', 'low'), 'deficient'),
    (('low', 'high', 'healthy', 'healthy', 'high', 'low', 'healthy'), 'deficient'),
    (('low', 'high', 'healthy', 'healthy', 'high', 'healthy', 'low'), 'average'),
    (('low', 'high', 'healthy', 'healthy', 'high', 'healthy', 'healthy'), 'average'),
    (('low', 'high', 'healthy', 'high', 'low', 'low', 'low'), 'deficient'),
    (('low', 'high', 'healthy', 'high', 'low', 'low', 'healthy'), 'deficient'),
    (('low', 'high', 'healthy', 'high', 'low', 'healthy', 'low'), 'deficient'),
    (('low', 'high', 'healthy', 'high', 'low', 'healthy', 'healthy'), 'average'),
    (('low', 'high', 'healthy', 'high', 'healthy', 'low', 'low'), 'average'),
    (('low', 'high', 'healthy', 'high', 'healthy', 'low', 'healthy'), 'average'),
    (('low', 'high', 'healthy', 'high', 'healthy', 'healthy', 'low'), 'average'),
    (('low', 'high', 'healthy', 'high', 'healthy', 'healthy', 'healthy'), 'average'),
    (('low', 'high', 'healthy', 'high', 'high', 'low', 'low'), 'deficient'),
    (('low', 'high', 'healthy', 'high', 'high', 'low', 'healthy'), 'deficient'),
    (('low', 'high', 'healthy', 'high', 'high', 'healthy', 'low'), 'deficient'),
    (('low', 'high', 'healthy', 'high', 'high', 'healthy', 'healthy'), 'average'),
    (('low', 'high', 'high', 'low', 'low', 'low', 'low'), 'deficient'),
    (('low', 'high', 'high', 'low', 'low', 'low', 'healthy'), 'deficient'),
    (('low', 'high', 'high', 'low', 'low', 'healthy', 'low'), 'deficient'),
    (('low', 'high', 'high', 'low', 'low', 'healthy', 'healthy'), 'deficient'),
    (('low', 'high', 'high', 'low', 'healthy', 'low', 'low'), 'deficient'),
    (('low', 'high', 'high', 'low', 'healthy', 'low', 'healthy'), 'deficient'),
    (('low', 'high', 'high', 'low', 'healthy', 'healthy', 'low'), 'deficient'),
    (('low', 'high', 'high', 'low', 'healthy', 'healthy', 'healthy'), 'average'),
    (('low', 'high', 'high', 'low', 'high', 'low', 'low'), 'deficient'),
    (('low', 'high', 'high', 'low', 'high', 'low', 'healthy'), 'deficient'),
    (('low', 'high', 'high', 'low', 'high', 'healthy', 'low'), 'deficient'),
    (('low', 'high', 'high', 'low', 'high', 'healthy', 'healthy'), 'deficient'),
    (('low', 'high', 'high', 'healthy', 'low', 'low', 'low'), 'deficient'),
    (('low', 'high', 'high', 'healthy', 'low', 'low', 'healthy'), 'deficient'),
    (('low', 'high', 'high', 'healthy', 'low', 'healthy', 'low'), 'deficient'),
    (('low', 'high', 'high', 'healthy', 'low', 'healthy', 'healthy'), 'deficient'),
    (('low', 'high', 'high', 'healthy', 'healthy', 'low', 'low'), 'deficient'),
    (('low', 'high', 'high', 'healthy', 'healthy', 'low', 'healthy'), 'deficient'),
    (('low', 'high', 'high', 'healthy', 'healthy', 'healthy', 'low'), 'average'),
    (('low', 'high', 'high', 'healthy', 'healthy', 'healthy', 'healthy'), 'average'),
    (('low', 'high', 'high', 'healthy', 'high', 'low', 'low'), 'deficient'),
    (('low', 'high', 'high', 'healthy', 'high', 'low', 'healthy'), 'deficient'),
    (('low', 'high', 'high', 'healthy', 'high', 'healthy', 'low'), 'deficient'),
    (('low', 'high', 'high', 'healthy', 'high', 'healthy', 'healthy'), 'deficient'),
    (('low', 'high', 'high', 'high', 'low', 'low', 'low'), 'deficient'),
    (('low', 'high', 'high', 'high', 'low', 'low', 'healthy'), 'deficient'),
    (('low', 'high', 'high', 'high', 'low', 'healthy', 'low'), 'deficient'),
    (('low', 'high', 'high', 'high', 'low', 'healthy', 'healthy'), 'deficient'),
    (('low', 'high', 'high', 'high', 'healthy', 'low', 'low'), 'deficient'),
    (('low', 'high', 'high', 'high', 'healthy', 'low', 'healthy'), 'deficient'),
    (('low', 'high', 'high', 'high', 'healthy', 'healthy', 'low'), 'deficient'),
    (('low', 'high', 'high', 'high', 'healthy', 'healthy', 'healthy'), 'average'),
    (('low', 'high', 'high', 'high', 'high', 'low', 'low'), 'deficient'),
    (('low', 'high', 'high', 'high', 'high', 'low', 'healthy'), 'deficient'),
    (('low', 'high', 'high', 'high', 'high', 'healthy', 'low'), 'deficient'),
    (('low', 'high', 'high', 'high', 'high', 'healthy', 'healthy'), 'deficient'),
    (('healthy', 'low', 'low', 'low', 'low', 'low', 'low'), 'average'),
    (('healthy', 'low', 'low', 'low', 'low', 'low', 'healthy'), 'average'),
    (('healthy', 'low', 'low', 'low', 'low', 'healthy', 'low'), 'average'),
    (('healthy', 'low', 'low', 'low', 'low', 'healthy', 'healthy'), 'average'),
    (('healthy', 'low', 'low', 'low', 'healthy', 'low', 'low'), 'average'),
    (('healthy', 'low', 'low', 'low', 'healthy', 'low', 'healthy'), 'average'),
    (('healthy', 'low', 'low', 'low', 'healthy', 'healthy', 'low'), 'average'),
    (('healthy', 'low', 'low', 'low', 'healthy', 'healthy', 'healthy'), 'average'),
    (('healthy', 'low', 'low', 'low', 'high', 'low', 'low'), 'average'),
    (('healthy', 'low', 'low', 'low', 'high', 'low', 'healthy'), 'average'),
    (('healthy', 'low', 'low', 'low', 'high', 'healthy', 'low'), 'average'),
    (('healthy', 'low', 'low', 'low', 'high', 'healthy', 'healthy'), 'average'),
    (('healthy', 'low', 'low', 'healthy', 'low', 'low', 'low'), 'average'),
    (('healthy', 'low', 'low', 'healthy', 'low', 'low', 'healthy'), 'average'),
    (('healthy', 'low', 'low', 'healthy', 'low', 'healthy', 'low'), 'average'),
    (('healthy', 'low', 'low', 'healthy', 'low', 'healthy', 'healthy'), 'average'),
    (('healthy', 'low', 'low', 'healthy', 'healthy', 'low', 'low'), 'average'),
    (('healthy', 'low', 'low', 'healthy', 'healthy', 'low', 'healthy'), 'average'),
    (('healthy', 'low', 'low', 'healthy', 'healthy', 'healthy', 'low'), 'average'),
    (('healthy', 'low', 'low', 'healthy', 'healthy', 'healthy', 'healthy'), 'average'),
    (('healthy', 'low', 'low', 'healthy', 'high', 'low', 'low'), 'average'),
    (('healthy', 'low', 'low', 'healthy', 'high', 'low', 'healthy'), 'average'),
    (('healthy', 'low', 'low', 'healthy', 'high', 'healthy', 'low'), 'average'),
    (('healthy', 'low', 'low', 'healthy', 'high', 'healthy', 'healthy'), 'average'),
    (('healthy', 'low', 'low', 'high', 'low', 'low', 'low'), 'average'),
    (('healthy', 'low', 'low', 'high', 'low', 'low', 'healthy'), 'average'),
    (('healthy', 'low', 'low', 'high', 'low', 'healthy', 'low'), 'average'),
    (('healthy', 'low', 'low', 'high', 'low', 'healthy', 'healthy'), 'average'),
    (('healthy', 'low', 'low', 'high', 'healthy', 'low', 'low'), 'average'),
    (('healthy', 'low', 'low', 'high', 'healthy', 'low', 'healthy'), 'average'),
    (('healthy', 'low', 'low', 'high', 'healthy', 'healthy', 'low'), 'average'),
    (('healthy', 'low', 'low', 'high', 'healthy', 'healthy', 'healthy'), 'average'),
    (('healthy', 'low', 'low', 'high', 'high', 'low', 'low'), 'average'),
    (('healthy', 'low', 'low', 'high', 'high', 'low', 'healthy'), 'average'),
    (('healthy', 'low', 'low', 'high', 'high', 'healthy', 'low'), 'average'),
    (('healthy', 'low', 'low', 'high', 'high', 'healthy', 'healthy'), 'average'),
    (('healthy', 'low', 'healthy', 'low', 'low', 'low', 'low'), 'average'),
    (('healthy', 'low', 'healthy', 'low', 'low', 'low', 'healthy'), 'average'),
    (('healthy', 'low', 'healthy', 'low', 'low', 'healthy', 'low'), 'average'),
    (('healthy', 'low', 'healthy', 'low', 'low', 'healthy', 'healthy'), 'average'),
    (('healthy', 'low', 'healthy', 'low', 'healthy', 'low', 'low'), 'average'),
    (('healthy', 'low', 'healthy', 'low', 'healthy', 'low', 'healthy'), 'average'),
    (('healthy', 'low', 'healthy', 'low', 'healthy', 'healthy', 'low'), 'average'),
    (('healthy', 'low', 'healthy', 'low', 'healthy', 'healthy', 'healthy'), 'excellent'),
    (('healthy', 'low', 'healthy', 'low', 'high', 'low', 'low'), 'average'),
    (('healthy', 'low', 'healthy', 'low', 'high', 'low', 'healthy'), 'average'),
    (('healthy', 'low', 'healthy', 'low', 'high', 'healthy', 'low'), 'average'),
    (('healthy', 'low', 'healthy', 'low', 'high', 'healthy', 'healthy'), 'average'),
    (('healthy', 'low', 'healthy', 'healthy', 'low', 'low', 'low'), 'average'),
    (('healthy', 'low', 'healthy', 'healthy', 'low', 'low', 'healthy'), 'average'),
    (('healthy', 'low', 'healthy', 'healthy', 'low', 'healthy', 'low'), 'average'),
    (('healthy', 'low', 'healthy', 'healthy', 'low', 'healthy', 'healthy'), 'average'),
    (('healthy', 'low', 'healthy', 'healthy', 'healthy', 'low', 'low'), 'average'),
    (('healthy', 'low', 'healthy', 'healthy', 'healthy', 'low', 'healthy'), 'average'),
    (('healthy', 'low', 'healthy', 'healthy', 'healthy', 'healthy', 'low'), 'excellent'),
    (('healthy', 'low', 'healthy', 'healthy', 'healthy', 'healthy', 'healthy'), 'excellent'),
    (('healthy', 'low', 'healthy', 'healthy', 'high', 'low', 'low'), 'average'),
    (('healthy', 'low', 'healthy', 'healthy', 'high', 'low', 'healthy'), 'average'),
    (('healthy', 'low', 'healthy', 'healthy', 'high', 'healthy', 'low'), 'average'),
    (('healthy', 'low', 'healthy', 'healthy', 'high', 'healthy', 'healthy'), 'average'),
    (('healthy', 'low', 'healthy', 'high', 'low', 'low', 'low'), 'average'),
    (('healthy', 'low', 'healthy', 'high', 'low', 'low', 'healthy'), 'average'),
    (('healthy', 'low', 'healthy', 'high', 'low', 'healthy', 'low'), 'average'),
    (('healthy', 'low', 'healthy', 'high', 'low', 'healthy', 'healthy'), 'average'),
    (('healthy', 'low', 'healthy', 'high', 'healthy', 'low', 'low'), 'average'),
    (('healthy', 'low', 'healthy', 'high', 'healthy', 'low', 'healthy'), 'average'),
    (('healthy', 'low', 'healthy', 'high', 'healthy', 'healthy', 'low'), 'average'),
    (('healthy', 'low', 'healthy', 'high', 'healthy', 'healthy', 'healthy'), 'excellent'),
    (('healthy', 'low', 'healthy', 'high', 'high', 'low', 'low'), 'average'),
    (('healthy', 'low', 'healthy', 'high', 'high', 'low', 'healthy'), 'average'),
    (('healthy', 'low', 'healthy', 'high', 'high', 'healthy', 'low'), 'average'),
    (('healthy', 'low', 'healthy', 'high', 'high', 'healthy', 'healthy'), 'average'),
    (('healthy', 'low', 'high', 'low', 'low', 'low', 'low'), 'average'),
    (('healthy', 'low', 'high', 'low', 'low', 'low', 'healthy'), 'average'),
    (('healthy', 'low', 'high', 'low', 'low', 'healthy', 'low'), 'average'),
    (('healthy', 'low', 'high', 'low', 'low', 'healthy', 'healthy'), 'average'),
    (('healthy', 'low', 'high', 'low', 'healthy', 'low', 'low'), 'average'),
    (('healthy', 'low', 'high', 'low', 'healthy', 'low', 'healthy'), 'average'),
    (('healthy', 'low', 'high', 'low', 'healthy', 'healthy', 'low'), 'average'),
    (('healthy', 'low', 'high', 'low', 'healthy', 'healthy', 'healthy'), 'average'),
    (('healthy', 'low', 'high', 'low', 'high', 'low', 'low'), 'average'),
    (('healthy', 'low', 'high', 'low', 'high', 'low', 'healthy'), 'average'),
    (('healthy', 'low', 'high', 'low', 'high', 'healthy', 'low'), 'average'),
    (('healthy', 'low', 'high', 'low', 'high', 'healthy', 'healthy'), 'average'),
    (('healthy', 'low', 'high', 'healthy', 'low', 'low', 'low'), 'average'),
    (('healthy', 'low', 'high', 'healthy', 'low', 'low', 'healthy'), 'average'),
    (('healthy', 'low', 'high', 'healthy', 'low', 'healthy', 'low'), 'average'),
    (('healthy', 'low', 'high', 'healthy', 'low', 'healthy', 'healthy'), 'average'),
    (('healthy', 'low', 'high', 'healthy', 'healthy', 'low', 'low'), 'average'),
    (('healthy', 'low', 'high', 'healthy', 'healthy', 'low', 'healthy'), 'average'),
    (('healthy', 'low', 'high', 'healthy', 'healthy', 'healthy', 'low'), 'average'),
    (('healthy', 'low', 'high', 'healthy', 'healthy', 'healthy', 'healthy'), 'average'),
    (('healthy', 'low', 'high', 'healthy', 'high', 'low', 'low'), 'average'),
    (('healthy', 'low', 'high', 'healthy', 'high', 'low', 'healthy'), 'average'),
    (('healthy', 'low', 'high', 'healthy', 'high', 'healthy', 'low'), 'average'),
    (('healthy', 'low', 'high', 'healthy', 'high', 'healthy', 'healthy'), 'average'),
    (('healthy', 'low', 'high', 'high', 'low', 'low', 'low'), 'average'),
    (('healthy', 'low', 'high', 'high', 'low', 'low', 'healthy'), 'average'),
    (('healthy', 'low', 'high', 'high', 'low', 'healthy', 'low'), 'average'),
    (('healthy', 'low', 'high', 'high', 'low', 'healthy', 'healthy'), 'average'),
    (('healthy', 'low', 'high', 'high', 'healthy', 'low', 'low'), 'average'),
    (('healthy', 'low', 'high', 'high', 'healthy', 'low', 'healthy'), 'average'),
    (('healthy', 'low', 'high', 'high', 'healthy', 'healthy', 'low'), 'average'),
    (('healthy', 'low', 'high', 'high', 'healthy', 'healthy', 'healthy'), 'average'),
    (('healthy', 'low', 'high', 'high', 'high', 'low', 'low'), 'average'),
    (('healthy', 'low', 'high', 'high', 'high', 'low', 'healthy'), 'average'),
    (('healthy', 'low', 'high', 'high', 'high', 'healthy', 'low'), 'average'),
    (('healthy', 'low', 'high', 'high', 'high', 'healthy', 'healthy'), 'average'),
    (('healthy', 'healthy', 'low', 'low', 'low', 'low', 'low'), 'average'),
    (('healthy', 'healthy', 'low', 'low', 'low', 'low', 'healthy'), 'average'),
    (('healthy', 'healthy', 'low', 'low', 'low', 'healthy', 'low'), 'average'),
    (('healthy', 'healthy', 'low', 'low', 'low', 'healthy', 'healthy'), 'average'),
    (('healthy', 'healthy', 'low', 'low', 'healthy', 'low', 'low'), 'average'),
    (('healthy', 'healthy', 'low', 'low', 'healthy', 'low', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'low', 'low', 'healthy', 'healthy', 'low'), 'excellent'),
    (('healthy', 'healthy', 'low', 'low', 'healthy', 'healthy', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'low', 'low', 'high', 'low', 'low'), 'average'),
    (('healthy', 'healthy', 'low', 'low', 'high', 'low', 'healthy'), 'average'),
    (('healthy', 'healthy', 'low', 'low', 'high', 'healthy', 'low'), 'average'),
    (('healthy', 'healthy', 'low', 'low', 'high', 'healthy', 'healthy'), 'average'),
    (('healthy', 'healthy', 'low', 'healthy', 'low', 'low', 'low'), 'average'),
    (('healthy', 'healthy', 'low', 'healthy', 'low', 'low', 'healthy'), 'average'),
    (('healthy', 'healthy', 'low', 'healthy', 'low', 'healthy', 'low'), 'average'),
    (('healthy', 'healthy', 'low', 'healthy', 'low', 'healthy', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'low', 'healthy', 'healthy', 'low', 'low'), 'excellent'),
    (('healthy', 'healthy', 'low', 'healthy', 'healthy', 'low', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'low', 'healthy', 'healthy', 'healthy', 'low'), 'excellent'),
    (('healthy', 'healthy', 'low', 'healthy', 'healthy', 'healthy', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'low', 'healthy', 'high', 'low', 'low'), 'average'),
    (('healthy', 'healthy', 'low', 'healthy', 'high', 'low', 'healthy'), 'average'),
    (('healthy', 'healthy', 'low', 'healthy', 'high', 'healthy', 'low'), 'average'),
    (('healthy', 'healthy', 'low', 'healthy', 'high', 'healthy', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'low', 'high', 'low', 'low', 'low'), 'average'),
    (('healthy', 'healthy', 'low', 'high', 'low', 'low', 'healthy'), 'average'),
    (('healthy', 'healthy', 'low', 'high', 'low', 'healthy', 'low'), 'average'),
    (('healthy', 'healthy', 'low', 'high', 'low', 'healthy', 'healthy'), 'average'),
    (('healthy', 'healthy', 'low', 'high', 'healthy', 'low', 'low'), 'average'),
    (('healthy', 'healthy', 'low', 'high', 'healthy', 'low', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'low', 'high', 'healthy', 'healthy', 'low'), 'excellent'),
    (('healthy', 'healthy', 'low', 'high', 'healthy', 'healthy', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'low', 'high', 'high', 'low', 'low'), 'average'),
    (('healthy', 'healthy', 'low', 'high', 'high', 'low', 'healthy'), 'average'),
    (('healthy', 'healthy', 'low', 'high', 'high', 'healthy', 'low'), 'average'),
    (('healthy', 'healthy', 'low', 'high', 'high', 'healthy', 'healthy'), 'average'),
    (('healthy', 'healthy', 'healthy', 'low', 'low', 'low', 'low'), 'average'),
    (('healthy', 'healthy', 'healthy', 'low', 'low', 'low', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'low', 'low', 'healthy', 'low'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'low', 'low', 'healthy', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'low', 'healthy', 'low', 'low'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'low', 'healthy', 'low', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'low', 'healthy', 'healthy', 'low'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'low', 'healthy', 'healthy', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'low', 'high', 'low', 'low'), 'average'),
    (('healthy', 'healthy', 'healthy', 'low', 'high', 'low', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'low', 'high', 'healthy', 'low'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'low', 'high', 'healthy', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'healthy', 'low', 'low', 'low'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'healthy', 'low', 'low', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'healthy', 'low', 'healthy', 'low'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'healthy', 'low', 'healthy', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'healthy', 'healthy', 'low', 'low'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'healthy', 'healthy', 'low', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'healthy', 'healthy', 'healthy', 'low'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'healthy', 'healthy', 'healthy', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'healthy', 'high', 'low', 'low'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'healthy', 'high', 'low', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'healthy', 'high', 'healthy', 'low'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'healthy', 'high', 'healthy', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'high', 'low', 'low', 'low'), 'average'),
    (('healthy', 'healthy', 'healthy', 'high', 'low', 'low', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'high', 'low', 'healthy', 'low'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'high', 'low', 'healthy', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'high', 'healthy', 'low', 'low'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'high', 'healthy', 'low', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'high', 'healthy', 'healthy', 'low'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'high', 'healthy', 'healthy', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'high', 'high', 'low', 'low'), 'average'),
    (('healthy', 'healthy', 'healthy', 'high', 'high', 'low', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'high', 'high', 'healthy', 'low'), 'excellent'),
    (('healthy', 'healthy', 'healthy', 'high', 'high', 'healthy', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'high', 'low', 'low', 'low', 'low'), 'average'),
    (('healthy', 'healthy', 'high', 'low', 'low', 'low', 'healthy'), 'average'),
    (('healthy', 'healthy', 'high', 'low', 'low', 'healthy', 'low'), 'average'),
    (('healthy', 'healthy', 'high', 'low', 'low', 'healthy', 'healthy'), 'average'),
    (('healthy', 'healthy', 'high', 'low', 'healthy', 'low', 'low'), 'average'),
    (('healthy', 'healthy', 'high', 'low', 'healthy', 'low', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'high', 'low', 'healthy', 'healthy', 'low'), 'excellent'),
    (('healthy', 'healthy', 'high', 'low', 'healthy', 'healthy', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'high', 'low', 'high', 'low', 'low'), 'average'),
    (('healthy', 'healthy', 'high', 'low', 'high', 'low', 'healthy'), 'average'),
    (('healthy', 'healthy', 'high', 'low', 'high', 'healthy', 'low'), 'average'),
    (('healthy', 'healthy', 'high', 'low', 'high', 'healthy', 'healthy'), 'average'),
    (('healthy', 'healthy', 'high', 'healthy', 'low', 'low', 'low'), 'average'),
    (('healthy', 'healthy', 'high', 'healthy', 'low', 'low', 'healthy'), 'average'),
    (('healthy', 'healthy', 'high', 'healthy', 'low', 'healthy', 'low'), 'average'),
    (('healthy', 'healthy', 'high', 'healthy', 'low', 'healthy', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'high', 'healthy', 'healthy', 'low', 'low'), 'excellent'),
    (('healthy', 'healthy', 'high', 'healthy', 'healthy', 'low', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'high', 'healthy', 'healthy', 'healthy', 'low'), 'excellent'),
    (('healthy', 'healthy', 'high', 'healthy', 'healthy', 'healthy', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'high', 'healthy', 'high', 'low', 'low'), 'average'),
    (('healthy', 'healthy', 'high', 'healthy', 'high', 'low', 'healthy'), 'average'),
    (('healthy', 'healthy', 'high', 'healthy', 'high', 'healthy', 'low'), 'average'),
    (('healthy', 'healthy', 'high', 'healthy', 'high', 'healthy', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'high', 'high', 'low', 'low', 'low'), 'average'),
    (('healthy', 'healthy', 'high', 'high', 'low', 'low', 'healthy'), 'average'),
    (('healthy', 'healthy', 'high', 'high', 'low', 'healthy', 'low'), 'average'),
    (('healthy', 'healthy', 'high', 'high', 'low', 'healthy', 'healthy'), 'average'),
    (('healthy', 'healthy', 'high', 'high', 'healthy', 'low', 'low'), 'average'),
    (('healthy', 'healthy', 'high', 'high', 'healthy', 'low', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'high', 'high', 'healthy', 'healthy', 'low'), 'excellent'),
    (('healthy', 'healthy', 'high', 'high', 'healthy', 'healthy', 'healthy'), 'excellent'),
    (('healthy', 'healthy', 'high', 'high', 'high', 'low', 'low'), 'average'),
    (('healthy', 'healthy', 'high', 'high', 'high', 'low', 'healthy'), 'average'),
    (('healthy', 'healthy', 'high', 'high', 'high', 'healthy', 'low'), 'average'),
    (('healthy', 'healthy', 'high', 'high', 'high', 'healthy', 'healthy'), 'average'),
    (('healthy', 'high', 'low', 'low', 'low', 'low', 'low'), 'average'),
    (('healthy', 'high', 'low', 'low', 'low', 'low', 'healthy'), 'average'),
    (('healthy', 'high', 'low', 'low', 'low', 'healthy', 'low'), 'average'),
    (('healthy', 'high', 'low', 'low', 'low', 'healthy', 'healthy'), 'average'),
    (('healthy', 'high', 'low', 'low', 'healthy', 'low', 'low'), 'average'),
    (('healthy', 'high', 'low', 'low', 'healthy', 'low', 'healthy'), 'average'),
    (('healthy', 'high', 'low', 'low', 'healthy', 'healthy', 'low'), 'average'),
    (('healthy', 'high', 'low', 'low', 'healthy', 'healthy', 'healthy'), 'average'),
    (('healthy', 'high', 'low', 'low', 'high', 'low', 'low'), 'average'),
    (('healthy', 'high', 'low', 'low', 'high', 'low', 'healthy'), 'average'),
    (('healthy', 'high', 'low', 'low', 'high', 'healthy', 'low'), 'average'),
    (('healthy', 'high', 'low', 'low', 'high', 'healthy', 'healthy'), 'average'),
    (('healthy', 'high', 'low', 'healthy', 'low', 'low', 'low'), 'average'),
    (('healthy', 'high', 'low', 'healthy', 'low', 'low', 'healthy'), 'average'),
    (('healthy', 'high', 'low', 'healthy', 'low', 'healthy', 'low'), 'average'),
    (('healthy', 'high', 'low', 'healthy', 'low', 'healthy', 'healthy'), 'average'),
    (('healthy', 'high', 'low', 'healthy', 'healthy', 'low', 'low'), 'average'),
    (('healthy', 'high', 'low', 'healthy', 'healthy', 'low', 'healthy'), 'average'),
    (('healthy', 'high', 'low', 'healthy', 'healthy', 'healthy', 'low'), 'average'),
    (('healthy', 'high', 'low', 'healthy', 'healthy', 'healthy', 'healthy'), 'average'),
    (('healthy', 'high', 'low', 'healthy', 'high', 'low', 'low'), 'average'),
    (('healthy', 'high', 'low', 'healthy', 'high', 'low', 'healthy'), 'average'),
    (('healthy', 'high', 'low', 'healthy', 'high', 'healthy', 'low'), 'average'),
    (('healthy', 'high', 'low', 'healthy', 'high', 'healthy', 'healthy'), 'average'),
    (('healthy', 'high', 'low', 'high', 'low', 'low', 'low'), 'average'),
    (('healthy', 'high', 'low', 'high', 'low', 'low', 'healthy'), 'average'),
    (('healthy', 'high', 'low', 'high', 'low', 'healthy', 'low'), 'average'),
    (('healthy', 'high', 'low', 'high', 'low', 'healthy', 'healthy'), 'average'),
    (('healthy', 'high', 'low', 'high', 'healthy', 'low', 'low'), 'average'),
    (('healthy', 'high', 'low', 'high', 'healthy', 'low', 'healthy'), 'average'),
    (('healthy', 'high', 'low', 'high', 'healthy', 'healthy', 'low'), 'average'),
    (('healthy', 'high', 'low', 'high', 'healthy', 'healthy', 'healthy'), 'average'),
    (('healthy', 'high', 'low', 'high', 'high', 'low', 'low'), 'average'),
    (('healthy', 'high', 'low', 'high', 'high', 'low', 'healthy'), 'average'),
    (('healthy', 'high', 'low', 'high', 'high', 'healthy', 'low'), 'average'),
    (('healthy', 'high', 'low', 'high', 'high', 'healthy', 'healthy'), 'average'),
    (('healthy', 'high', 'healthy', 'low', 'low', 'low', 'low'), 'average'),
    (('healthy', 'high', 'healthy', 'low', 'low', 'low', 'healthy'), 'average'),
    (('healthy', 'high', 'healthy', 'low', 'low', 'healthy', 'low'), 'average'),
    (('healthy', 'high', 'healthy', 'low', 'low', 'healthy', 'healthy'), 'average'),
    (('healthy', 'high', 'healthy', 'low', 'healthy', 'low', 'low'), 'average'),
    (('healthy', 'high', 'healthy', 'low', 'healthy', 'low', 'healthy'), 'average'),
    (('healthy', 'high', 'healthy', 'low', 'healthy', 'healthy', 'low'), 'average'),
    (('healthy', 'high', 'healthy', 'low', 'healthy', 'healthy', 'healthy'), 'excellent'),
    (('healthy', 'high', 'healthy', 'low', 'high', 'low', 'low'), 'average'),
    (('healthy', 'high', 'healthy', 'low', 'high', 'low', 'healthy'), 'average'),
    (('healthy', 'high', 'healthy', 'low', 'high', 'healthy', 'low'), 'average'),
    (('healthy', 'high', 'healthy', 'low', 'high', 'healthy', 'healthy'), 'average'),
    (('healthy', 'high', 'healthy', 'healthy', 'low', 'low', 'low'), 'average'),
    (('healthy', 'high', 'healthy', 'healthy', 'low', 'low', 'healthy'), 'average'),
    (('healthy', 'high', 'healthy', 'healthy', 'low', 'healthy', 'low'), 'average'),
    (('healthy', 'high', 'healthy', 'healthy', 'low', 'healthy', 'healthy'), 'average'),
    (('healthy', 'high', 'healthy', 'healthy', 'healthy', 'low', 'low'), 'average'),
    (('healthy', 'high', 'healthy', 'healthy', 'healthy', 'low', 'healthy'), 'average'),
    (('healthy', 'high', 'healthy', 'healthy', 'healthy', 'healthy', 'low'), 'excellent'),
    (('healthy', 'high', 'healthy', 'healthy', 'healthy', 'healthy', 'healthy'), 'excellent'),
    (('healthy', 'high', 'healthy', 'healthy', 'high', 'low', 'low'), 'average'),
    (('healthy', 'high', 'healthy', 'healthy', 'high', 'low', 'healthy'), 'average'),
    (('healthy', 'high', 'healthy', 'healthy', 'high', 'healthy', 'low'), 'average'),
    (('healthy', 'high', 'healthy', 'healthy', 'high', 'healthy', 'healthy'), 'average'),
    (('healthy', 'high', 'healthy', 'high', 'low', 'low', 'low'), 'average'),
    (('healthy', 'high', 'healthy', 'high', 'low', 'low', 'healthy'), 'average'),
    (('healthy', 'high', 'healthy', 'high', 'low', 'healthy', 'low'), 'average'),
    (('healthy', 'high', 'healthy', 'high', 'low', 'healthy', 'healthy'), 'average'),
    (('healthy', 'high', 'healthy', 'high', 'healthy', 'low', 'low'), 'average'),
    (('healthy', 'high', 'healthy', 'high', 'healthy', 'low', 'healthy'), 'average'),
    (('healthy', 'high', 'healthy', 'high', 'healthy', 'healthy', 'low'), 'average'),
    (('healthy', 'high', 'healthy', 'high', 'healthy', 'healthy', 'healthy'), 'excellent'),
    (('healthy', 'high', 'healthy', 'high', 'high', 'low', 'low'), 'average'),
    (('healthy', 'high', 'healthy', 'high', 'high', 'low', 'healthy'), 'average'),
    (('healthy', 'high', 'healthy', 'high', 'high', 'healthy', 'low'), 'average'),
    (('healthy', 'high', 'healthy', 'high', 'high', 'healthy', 'healthy'), 'average'),
    (('healthy', 'high', 'high', 'low', 'low', 'low', 'low'), 'average'),
    (('healthy', 'high', 'high', 'low', 'low', 'low', 'healthy'), 'average'),
    (('healthy', 'high', 'high', 'low', 'low', 'healthy', 'low'), 'average'),
    (('healthy', 'high', 'high', 'low', 'low', 'healthy', 'healthy'), 'average'),
    (('healthy', 'high', 'high', 'low', 'healthy', 'low', 'low'), 'average'),
    (('healthy', 'high', 'high', 'low', 'healthy', 'low', 'healthy'), 'average'),
    (('healthy', 'high', 'high', 'low', 'healthy', 'healthy', 'low'), 'average'),
    (('healthy', 'high', 'high', 'low', 'healthy', 'healthy', 'healthy'), 'average'),
    (('healthy', 'high', 'high', 'low', 'high', 'low', 'low'), 'average'),
    (('healthy', 'high', 'high', 'low', 'high', 'low', 'healthy'), 'average'),
    (('healthy', 'high', 'high', 'low', 'high', 'healthy', 'low'), 'average'),
    (('healthy', 'high', 'high', 'low', 'high', 'healthy', 'healthy'), 'average'),
    (('healthy', 'high', 'high', 'healthy', 'low', 'low', 'low'), 'average'),
    (('healthy', 'high', 'high', 'healthy', 'low', 'low', 'healthy'), 'average'),
    (('healthy', 'high', 'high', 'healthy', 'low', 'healthy', 'low'), 'average'),
    (('healthy', 'high', 'high', 'healthy', 'low', 'healthy', 'healthy'), 'average'),
    (('healthy', 'high', 'high', 'healthy', 'healthy', 'low', 'low'), 'average'),
    (('healthy', 'high', 'high', 'healthy', 'healthy', 'low', 'healthy'), 'average'),
    (('healthy', 'high', 'high', 'healthy', 'healthy', 'healthy', 'low'), 'average'),
    (('healthy', 'high', 'high', 'healthy', 'healthy', 'healthy', 'healthy'), 'average'),
    (('healthy', 'high', 'high', 'healthy', 'high', 'low', 'low'), 'average'),
    (('healthy', 'high', 'high', 'healthy', 'high', 'low', 'healthy'), 'average'),
    (('healthy', 'high', 'high', 'healthy', 'high', 'healthy', 'low'), 'average'),
    (('healthy', 'high', 'high', 'healthy', 'high', 'healthy', 'healthy'), 'average'),
    (('healthy', 'high', 'high', 'high', 'low', 'low', 'low'), 'average'),
    (('healthy', 'high', 'high', 'high', 'low', 'low', 'healthy'), 'average'),
    (('healthy', 'high', 'high', 'high', 'low', 'healthy', 'low'), 'average'),
    (('healthy', 'high', 'high', 'high', 'low', 'healthy', 'healthy'), 'average'),
    (('healthy', 'high', 'high', 'high', 'healthy', 'low', 'low'), 'average'),
    (('healthy', 'high', 'high', 'high', 'healthy', 'low', 'healthy'), 'average'),
    (('healthy', 'high', 'high', 'high', 'healthy', 'healthy', 'low'), 'average'),
    (('healthy', 'high', 'high', 'high', 'healthy', 'healthy', 'healthy'), 'average'),
    (('healthy', 'high', 'high', 'high', 'high', 'low', 'low'), 'average'),
    (('healthy', 'high', 'high', 'high', 'high', 'low', 'healthy'), 'average'),
    (('healthy', 'high', 'high', 'high', 'high', 'healthy', 'low'), 'average'),
    (('healthy', 'high', 'high', 'high', 'high', 'healthy', 'healthy'), 'average'),
    (('high', 'low', 'low', 'low', 'low', 'low', 'low'), 'deficient'),
    (('high', 'low', 'low', 'low', 'low', 'low', 'healthy'), 'deficient'),
    (('high', 'low', 'low', 'low', 'low', 'healthy', 'low'), 'deficient'),
    (('high', 'low', 'low', 'low', 'low', 'healthy', 'healthy'), 'deficient'),
    (('high', 'low', 'low', 'low', 'healthy', 'low', 'low'), 'deficient'),
    (('high', 'low', 'low', 'low', 'healthy', 'low', 'healthy'), 'deficient'),
    (('high', 'low', 'low', 'low', 'healthy', 'healthy', 'low'), 'deficient'),
    (('high', 'low', 'low', 'low', 'healthy', 'healthy', 'healthy'), 'average'),
    (('high', 'low', 'low', 'low', 'high', 'low', 'low'), 'deficient'),
    (('high', 'low', 'low', 'low', 'high', 'low', 'healthy'), 'deficient'),
    (('high', 'low', 'low', 'low', 'high', 'healthy', 'low'), 'deficient'),
    (('high', 'low', 'low', 'low', 'high', 'healthy', 'healthy'), 'deficient'),
    (('high', 'low', 'low', 'healthy', 'low', 'low', 'low'), 'deficient'),
    (('high', 'low', 'low', 'healthy', 'low', 'low', 'healthy'), 'deficient'),
    (('high', 'low', 'low', 'healthy', 'low', 'healthy', 'low'), 'deficient'),
    (('high', 'low', 'low', 'healthy', 'low', 'healthy', 'healthy'), 'deficient'),
    (('high', 'low', 'low', 'healthy', 'healthy', 'low', 'low'), 'deficient'),
    (('high', 'low', 'low', 'healthy', 'healthy', 'low', 'healthy'), 'deficient'),
    (('high', 'low', 'low', 'healthy', 'healthy', 'healthy', 'low'), 'average'),
    (('high', 'low', 'low', 'healthy', 'healthy', 'healthy', 'healthy'), 'average'),
    (('high', 'low', 'low', 'healthy', 'high', 'low', 'low'), 'deficient'),
    (('high', 'low', 'low', 'healthy', 'high', 'low', 'healthy'), 'deficient'),
    (('high', 'low', 'low', 'healthy', 'high', 'healthy', 'low'), 'deficient'),
    (('high', 'low', 'low', 'healthy', 'high', 'healthy', 'healthy'), 'deficient'),
    (('high', 'low', 'low', 'high', 'low', 'low', 'low'), 'deficient'),
    (('high', 'low', 'low', 'high', 'low', 'low', 'healthy'), 'deficient'),
    (('high', 'low', 'low', 'high', 'low', 'healthy', 'low'), 'deficient'),
    (('high', 'low', 'low', 'high', 'low', 'healthy', 'healthy'), 'deficient'),
    (('high', 'low', 'low', 'high', 'healthy', 'low', 'low'), 'deficient'),
    (('high', 'low', 'low', 'high', 'healthy', 'low', 'healthy'), 'deficient'),
    (('high', 'low', 'low', 'high', 'healthy', 'healthy', 'low'), 'deficient'),
    (('high', 'low', 'low', 'high', 'healthy', 'healthy', 'healthy'), 'average'),
    (('high', 'low', 'low', 'high', 'high', 'low', 'low'), 'deficient'),
    (('high', 'low', 'low', 'high', 'high', 'low', 'healthy'), 'deficient'),
    (('high', 'low', 'low', 'high', 'high', 'healthy', 'low'), 'deficient'),
    (('high', 'low', 'low', 'high', 'high', 'healthy', 'healthy'), 'deficient'),
    (('high', 'low', 'healthy', 'low', 'low', 'low', 'low'), 'deficient'),
    (('high', 'low', 'healthy', 'low', 'low', 'low', 'healthy'), 'deficient'),
    (('high', 'low', 'healthy', 'low', 'low', 'healthy', 'low'), 'deficient'),
    (('high', 'low', 'healthy', 'low', 'low', 'healthy', 'healthy'), 'average'),
    (('high', 'low', 'healthy', 'low', 'healthy', 'low', 'low'), 'average'),
    (('high', 'low', 'healthy', 'low', 'healthy', 'low', 'healthy'), 'average'),
    (('high', 'low', 'healthy', 'low', 'healthy', 'healthy', 'low'), 'average'),
    (('high', 'low', 'healthy', 'low', 'healthy', 'healthy', 'healthy'), 'average'),
    (('high', 'low', 'healthy', 'low', 'high', 'low', 'low'), 'deficient'),
    (('high', 'low', 'healthy', 'low', 'high', 'low', 'healthy'), 'deficient'),
    (('high', 'low', 'healthy', 'low', 'high', 'healthy', 'low'), 'deficient'),
    (('high', 'low', 'healthy', 'low', 'high', 'healthy', 'healthy'), 'average'),
    (('high', 'low', 'healthy', 'healthy', 'low', 'low', 'low'), 'deficient'),
    (('high', 'low', 'healthy', 'healthy', 'low', 'low', 'healthy'), 'deficient'),
    (('high', 'low', 'healthy', 'healthy', 'low', 'healthy', 'low'), 'average'),
    (('high', 'low', 'healthy', 'healthy', 'low', 'healthy', 'healthy'), 'average'),
    (('high', 'low', 'healthy', 'healthy', 'healthy', 'low', 'low'), 'average'),
    (('high', 'low', 'healthy', 'healthy', 'healthy', 'low', 'healthy'), 'average'),
    (('high', 'low', 'healthy', 'healthy', 'healthy', 'healthy', 'low'), 'average'),
    (('high', 'low', 'healthy', 'healthy', 'healthy', 'healthy', 'healthy'), 'average'),
    (('high', 'low', 'healthy', 'healthy', 'high', 'low', 'low'), 'deficient'),
    (('high', 'low', 'healthy', 'healthy', 'high', 'low', 'healthy'), 'deficient'),
    (('high', 'low', 'healthy', 'healthy', 'high', 'healthy', 'low'), 'average'),
    (('high', 'low', 'healthy', 'healthy', 'high', 'healthy', 'healthy'), 'average'),
    (('high', 'low', 'healthy', 'high', 'low', 'low', 'low'), 'deficient'),
    (('high', 'low', 'healthy', 'high', 'low', 'low', 'healthy'), 'deficient'),
    (('high', 'low', 'healthy', 'high', 'low', 'healthy', 'low'), 'deficient'),
    (('high', 'low', 'healthy', 'high', 'low', 'healthy', 'healthy'), 'average'),
    (('high', 'low', 'healthy', 'high', 'healthy', 'low', 'low'), 'average'),
    (('high', 'low', 'healthy', 'high', 'healthy', 'low', 'healthy'), 'average'),
    (('high', 'low', 'healthy', 'high', 'healthy', 'healthy', 'low'), 'average'),
    (('high', 'low', 'healthy', 'high', 'healthy', 'healthy', 'healthy'), 'average'),
    (('high', 'low', 'healthy', 'high', 'high', 'low', 'low'), 'deficient'),
    (('high', 'low', 'healthy', 'high', 'high', 'low', 'healthy'), 'deficient'),
    (('high', 'low', 'healthy', 'high', 'high', 'healthy', 'low'), 'deficient'),
    (('high', 'low', 'healthy', 'high', 'high', 'healthy', 'healthy'), 'average'),
    (('high', 'low', 'high', 'low', 'low', 'low', 'low'), 'deficient'),
    (('high', 'low', 'high', 'low', 'low', 'low', 'healthy'), 'deficient'),
    (('high', 'low', 'high', 'low', 'low', 'healthy', 'low'), 'deficient'),
    (('high', 'low', 'high', 'low', 'low', 'healthy', 'healthy'), 'deficient'),
    (('high', 'low', 'high', 'low', 'healthy', 'low', 'low'), 'deficient'),
    (('high', 'low', 'high', 'low', 'healthy', 'low', 'healthy'), 'deficient'),
    (('high', 'low', 'high', 'low', 'healthy', 'healthy', 'low'), 'deficient'),
    (('high', 'low', 'high', 'low', 'healthy', 'healthy', 'healthy'), 'average'),
    (('high', 'low', 'high', 'low', 'high', 'low', 'low'), 'deficient'),
    (('high', 'low', 'high', 'low', 'high', 'low', 'healthy'), 'deficient'),
    (('high', 'low', 'high', 'low', 'high', 'healthy', 'low'), 'deficient'),
    (('high', 'low', 'high', 'low', 'high', 'healthy', 'healthy'), 'deficient'),
    (('high', 'low', 'high', 'healthy', 'low', 'low', 'low'), 'deficient'),
    (('high', 'low', 'high', 'healthy', 'low', 'low', 'healthy'), 'deficient'),
    (('high', 'low', 'high', 'healthy', 'low', 'healthy', 'low'), 'deficient'),
    (('high', 'low', 'high', 'healthy', 'low', 'healthy', 'healthy'), 'deficient'),
    (('high', 'low', 'high', 'healthy', 'healthy', 'low', 'low'), 'deficient'),
    (('high', 'low', 'high', 'healthy', 'healthy', 'low', 'healthy'), 'deficient'),
    (('high', 'low', 'high', 'healthy', 'healthy', 'healthy', 'low'), 'average'),
    (('high', 'low', 'high', 'healthy', 'healthy', 'healthy', 'healthy'), 'average'),
    (('high', 'low', 'high', 'healthy', 'high', 'low', 'low'), 'deficient'),
    (('high', 'low', 'high', 'healthy', 'high', 'low', 'healthy'), 'deficient'),
    (('high', 'low', 'high', 'healthy', 'high', 'healthy', 'low'), 'deficient'),
    (('high', 'low', 'high', 'healthy', 'high', 'healthy', 'healthy'), 'deficient'),
    (('high', 'low', 'high', 'high', 'low', 'low', 'low'), 'deficient'),
    (('high', 'low', 'high', 'high', 'low', 'low', 'healthy'), 'deficient'),
    (('high', 'low', 'high', 'high', 'low', 'healthy', 'low'), 'deficient'),
    (('high', 'low', 'high', 'high', 'low', 'healthy', 'healthy'), 'deficient'),
    (('high', 'low', 'high', 'high', 'healthy', 'low', 'low'), 'deficient'),
    (('high', 'low', 'high', 'high', 'healthy', 'low', 'healthy'), 'deficient'),
    (('high', 'low', 'high', 'high', 'healthy', 'healthy', 'low'), 'deficient'),
    (('high', 'low', 'high', 'high', 'healthy', 'healthy', 'healthy'), 'average'),
    (('high', 'low', 'high', 'high', 'high', 'low', 'low'), 'deficient'),
    (('high', 'low', 'high', 'high', 'high', 'low', 'healthy'), 'deficient'),
    (('high', 'low', 'high', 'high', 'high', 'healthy', 'low'), 'deficient'),
    (('high', 'low', 'high', 'high', 'high', 'healthy', 'healthy'), 'deficient'),
    (('high', 'healthy', 'low', 'low', 'low', 'low', 'low'), 'deficient'),
    (('high', 'healthy', 'low', 'low', 'low', 'low', 'healthy'), 'deficient'),
    (('high', 'healthy', 'low', 'low', 'low', 'healthy', 'low'), 'average'),
    (('high', 'healthy', 'low', 'low', 'low', 'healthy', 'healthy'), 'average'),
    (('high', 'healthy', 'low', 'low', 'healthy', 'low', 'low'), 'average'),
    (('high', 'healthy', 'low', 'low', 'healthy', 'low', 'healthy'), 'average'),
    (('high', 'healthy', 'low', 'low', 'healthy', 'healthy', 'low'), 'average'),
    (('high', 'healthy', 'low', 'low', 'healthy', 'healthy', 'healthy'), 'average'),
    (('high', 'healthy', 'low', 'low', 'high', 'low', 'low'), 'deficient'),
    (('high', 'healthy', 'low', 'low', 'high', 'low', 'healthy'), 'deficient'),
    (('high', 'healthy', 'low', 'low', 'high', 'healthy', 'low'), 'average'),
    (('high', 'healthy', 'low', 'low', 'high', 'healthy', 'healthy'), 'average'),
    (('high', 'healthy', 'low', 'healthy', 'low', 'low', 'low'), 'deficient'),
    (('high', 'healthy', 'low', 'healthy', 'low', 'low', 'healthy'), 'average'),
    (('high', 'healthy', 'low', 'healthy', 'low', 'healthy', 'low'), 'average'),
    (('high', 'healthy', 'low', 'healthy', 'low', 'healthy', 'healthy'), 'average'),
    (('high', 'healthy', 'low', 'healthy', 'healthy', 'low', 'low'), 'average'),
    (('high', 'healthy', 'low', 'healthy', 'healthy', 'low', 'healthy'), 'average'),
    (('high', 'healthy', 'low', 'healthy', 'healthy', 'healthy', 'low'), 'average'),
    (('high', 'healthy', 'low', 'healthy', 'healthy', 'healthy', 'healthy'), 'average'),
    (('high', 'healthy', 'low', 'healthy', 'high', 'low', 'low'), 'deficient'),
    (('high', 'healthy', 'low', 'healthy', 'high', 'low', 'healthy'), 'average'),
    (('high', 'healthy', 'low', 'healthy', 'high', 'healthy', 'low'), 'average'),
    (('high', 'healthy', 'low', 'healthy', 'high', 'healthy', 'healthy'), 'average'),
    (('high', 'healthy', 'low', 'high', 'low', 'low', 'low'), 'deficient'),
    (('high', 'healthy', 'low', 'high', 'low', 'low', 'healthy'), 'deficient'),
    (('high', 'healthy', 'low', 'high', 'low', 'healthy', 'low'), 'average'),
    (('high', 'healthy', 'low', 'high', 'low', 'healthy', 'healthy'), 'average'),
    (('high', 'healthy', 'low', 'high', 'healthy', 'low', 'low'), 'average'),
    (('high', 'healthy', 'low', 'high', 'healthy', 'low', 'healthy'), 'average'),
    (('high', 'healthy', 'low', 'high', 'healthy', 'healthy', 'low'), 'average'),
    (('high', 'healthy', 'low', 'high', 'healthy', 'healthy', 'healthy'), 'average'),
    (('high', 'healthy', 'low', 'high', 'high', 'low', 'low'), 'deficient'),
    (('high', 'healthy', 'low', 'high', 'high', 'low', 'healthy'), 'deficient'),
    (('high', 'healthy', 'low', 'high', 'high', 'healthy', 'low'), 'average'),
    (('high', 'healthy', 'low', 'high', 'high', 'healthy', 'healthy'), 'average'),
    (('high', 'healthy', 'healthy', 'low', 'low', 'low', 'low'), 'average'),
    (('high', 'healthy', 'healthy', 'low', 'low', 'low', 'healthy'), 'average'),
    (('high', 'healthy', 'healthy', 'low', 'low', 'healthy', 'low'), 'average'),
    (('high', 'healthy', 'healthy', 'low', 'low', 'healthy', 'healthy'), 'average'),
    (('high', 'healthy', 'healthy', 'low', 'healthy', 'low', 'low'), 'average'),
    (('high', 'healthy', 'healthy', 'low', 'healthy', 'low', 'healthy'), 'average'),
    (('high', 'healthy', 'healthy', 'low', 'healthy', 'healthy', 'low'), 'average'),
    (('high', 'healthy', 'healthy', 'low', 'healthy', 'healthy', 'healthy'), 'average'),
    (('high', 'healthy', 'healthy', 'low', 'high', 'low', 'low'), 'average'),
    (('high', 'healthy', 'healthy', 'low', 'high', 'low', 'healthy'), 'average'),
    (('high', 'healthy', 'healthy', 'low', 'high', 'healthy', 'low'), 'average'),
    (('high', 'healthy', 'healthy', 'low', 'high', 'healthy', 'healthy'), 'average'),
    (('high', 'healthy', 'healthy', 'healthy', 'low', 'low', 'low'), 'average'),
    (('high', 'healthy', 'healthy', 'healthy', 'low', 'low', 'healthy'), 'average'),
    (('high', 'healthy', 'healthy', 'healthy', 'low', 'healthy', 'low'), 'average'),
    (('high', 'healthy', 'healthy', 'healthy', 'low', 'healthy', 'healthy'), 'average'),
    (('high', 'healthy', 'healthy', 'healthy', 'healthy', 'low', 'low'), 'average'),
    (('high', 'healthy', 'healthy', 'healthy', 'healthy', 'low', 'healthy'), 'average'),
    (('high', 'healthy', 'healthy', 'healthy', 'healthy', 'healthy', 'low'), 'average'),
    (('high', 'healthy', 'healthy', 'healthy', 'healthy', 'healthy', 'healthy'), 'average'),
    (('high', 'healthy', 'healthy', 'healthy', 'high', 'low', 'low'), 'average'),
    (('high', 'healthy', 'healthy', 'healthy', 'high', 'low', 'healthy'), 'average'),
    (('high', 'healthy', 'healthy', 'healthy', 'high', 'healthy', 'low'), 'average'),
    (('high', 'healthy', 'healthy', 'healthy', 'high', 'healthy', 'healthy'), 'average'),
    (('high', 'healthy', 'healthy', 'high', 'low', 'low', 'low'), 'average'),
    (('high', 'healthy', 'healthy', 'high', 'low', 'low', 'healthy'), 'average'),
    (('high', 'healthy', 'healthy', 'high', 'low', 'healthy', 'low'), 'average'),
    (('high', 'healthy', 'healthy', 'high', 'low', 'healthy', 'healthy'), 'average'),
    (('high', 'healthy', 'healthy', 'high', 'healthy', 'low', 'low'), 'average'),
    (('high', 'healthy', 'healthy', 'high', 'healthy', 'low', 'healthy'), 'average'),
    (('high', 'healthy', 'healthy', 'high', 'healthy', 'healthy', 'low'), 'average'),
    (('high', 'healthy', 'healthy', 'high', 'healthy', 'healthy', 'healthy'), 'average'),
    (('high', 'healthy', 'healthy', 'high', 'high', 'low', 'low'), 'average'),
    (('high', 'healthy', 'healthy', 'high', 'high', 'low', 'healthy'), 'average'),
    (('high', 'healthy', 'healthy', 'high', 'high', 'healthy', 'low'), 'average'),
    (('high', 'healthy', 'healthy', 'high', 'high', 'healthy', 'healthy'), 'average'),
    (('high', 'healthy', 'high', 'low', 'low', 'low', 'low'), 'deficient'),
    (('high', 'healthy', 'high', 'low', 'low', 'low', 'healthy'), 'deficient'),
    (('high', 'healthy', 'high', 'low', 'low', 'healthy', 'low'), 'average'),
    (('high', 'healthy', 'high', 'low', 'low', 'healthy', 'healthy'), 'average'),
    (('high', 'healthy', 'high', 'low', 'healthy', 'low', 'low'), 'average'),
    (('high', 'healthy', 'high', 'low', 'healthy', 'low', 'healthy'), 'average'),
    (('high', 'healthy', 'high', 'low', 'healthy', 'healthy', 'low'), 'average'),
    (('high', 'healthy', 'high', 'low', 'healthy', 'healthy', 'healthy'), 'average'),
    (('high', 'healthy', 'high', 'low', 'high', 'low', 'low'), 'deficient'),
    (('high', 'healthy', 'high', 'low', 'high', 'low', 'healthy'), 'deficient'),
    (('high', 'healthy', 'high', 'low', 'high', 'healthy', 'low'), 'average'),
    (('high', 'healthy', 'high', 'low', 'high', 'healthy', 'healthy'), 'average'),
    (('high', 'healthy', 'high', 'healthy', 'low', 'low', 'low'), 'deficient'),
    (('high', 'healthy', 'high', 'healthy', 'low', 'low', 'healthy'), 'average'),
    (('high', 'healthy', 'high', 'healthy', 'low', 'healthy', 'low'), 'average'),
    (('high', 'healthy', 'high', 'healthy', 'low', 'healthy', 'healthy'), 'average'),
    (('high', 'healthy', 'high', 'healthy', 'healthy', 'low', 'low'), 'average'),
    (('high', 'healthy', 'high', 'healthy', 'healthy', 'low', 'healthy'), 'average'),
    (('high', 'healthy', 'high', 'healthy', 'healthy', 'healthy', 'low'), 'average'),
    (('high', 'healthy', 'high', 'healthy', 'healthy', 'healthy', 'healthy'), 'average'),
    (('high', 'healthy', 'high', 'healthy', 'high', 'low', 'low'), 'deficient'),
    (('high', 'healthy', 'high', 'healthy', 'high', 'low', 'healthy'), 'average'),
    (('high', 'healthy', 'high', 'healthy', 'high', 'healthy', 'low'), 'average'),
    (('high', 'healthy', 'high', 'healthy', 'high', 'healthy', 'healthy'), 'average'),
    (('high', 'healthy', 'high', 'high', 'low', 'low', 'low'), 'deficient'),
    (('high', 'healthy', 'high', 'high', 'low', 'low', 'healthy'), 'deficient'),
    (('high', 'healthy', 'high', 'high', 'low', 'healthy', 'low'), 'average'),
    (('high', 'healthy', 'high', 'high', 'low', 'healthy', 'healthy'), 'average'),
    (('high', 'healthy', 'high', 'high', 'healthy', 'low', 'low'), 'average'),
    (('high', 'healthy', 'high', 'high', 'healthy', 'low', 'healthy'), 'average'),
    (('high', 'healthy', 'high', 'high', 'healthy', 'healthy', 'low'), 'average'),
    (('high', 'healthy', 'high', 'high', 'healthy', 'healthy', 'healthy'), 'average'),
    (('high', 'healthy', 'high', 'high', 'high', 'low', 'low'), 'deficient'),
    (('high', 'healthy', 'high', 'high', 'high', 'low', 'healthy'), 'deficient'),
    (('high', 'healthy', 'high', 'high', 'high', 'healthy', 'low'), 'average'),
    (('high', 'healthy', 'high', 'high', 'high', 'healthy', 'healthy'), 'average'),
    (('high', 'high', 'low', 'low', 'low', 'low', 'low'), 'deficient'),
    (('high', 'high', 'low', 'low', 'low', 'low', 'healthy'), 'deficient'),
    (('high', 'high', 'low', 'low', 'low', 'healthy', 'low'), 'deficient'),
    (('high', 'high', 'low', 'low', 'low', 'healthy', 'healthy'), 'deficient'),
    (('high', 'high', 'low', 'low', 'healthy', 'low', 'low'), 'deficient'),
    (('high', 'high', 'low', 'low', 'healthy', 'low', 'healthy'), 'deficient'),
    (('high', 'high', 'low', 'low', 'healthy', 'healthy', 'low'), 'deficient'),
    (('high', 'high', 'low', 'low', 'healthy', 'healthy', 'healthy'), 'average'),
    (('high', 'high', 'low', 'low', 'high', 'low', 'low'), 'deficient'),
    (('high', 'high', 'low', 'low', 'high', 'low', 'healthy'), 'deficient'),
    (('high', 'high', 'low', 'low', 'high', 'healthy', 'low'), 'deficient'),
    (('high', 'high', 'low', 'low', 'high', 'healthy', 'healthy'), 'deficient'),
    (('high', 'high', 'low', 'healthy', 'low', 'low', 'low'), 'deficient'),
    (('high', 'high', 'low', 'healthy', 'low', 'low', 'healthy'), 'deficient'),
    (('high', 'high', 'low', 'healthy', 'low', 'healthy', 'low'), 'deficient'),
    (('high', 'high', 'low', 'healthy', 'low', 'healthy', 'healthy'), 'deficient'),
    (('high', 'high', 'low', 'healthy', 'healthy', 'low', 'low'), 'deficient'),
    (('high', 'high', 'low', 'healthy', 'healthy', 'low', 'healthy'), 'deficient'),
    (('high', 'high', 'low', 'healthy', 'healthy', 'healthy', 'low'), 'average'),
    (('high', 'high', 'low', 'healthy', 'healthy', 'healthy', 'healthy'), 'average'),
    (('high', 'high', 'low', 'healthy', 'high', 'low', 'low'), 'deficient'),
    (('high', 'high', 'low', 'healthy', 'high', 'low', 'healthy'), 'deficient'),
    (('high', 'high', 'low', 'healthy', 'high', 'healthy', 'low'), 'deficient'),
    (('high', 'high', 'low', 'healthy', 'high', 'healthy', 'healthy'), 'deficient'),
    (('high', 'high', 'low', 'high', 'low', 'low', 'low'), 'deficient'),
    (('high', 'high', 'low', 'high', 'low', 'low', 'healthy'), 'deficient'),
    (('high', 'high', 'low', 'high', 'low', 'healthy', 'low'), 'deficient'),
    (('high', 'high', 'low', 'high', 'low', 'healthy', 'healthy'), 'deficient'),
    (('high', 'high', 'low', 'high', 'healthy', 'low', 'low'), 'deficient'),
    (('high', 'high', 'low', 'high', 'healthy', 'low', 'healthy'), 'deficient'),
    (('high', 'high', 'low', 'high', 'healthy', 'healthy', 'low'), 'deficient'),
    (('high', 'high', 'low', 'high', 'healthy', 'healthy', 'healthy'), 'average'),
    (('high', 'high', 'low', 'high', 'high', 'low', 'low'), 'deficient'),
    (('high', 'high', 'low', 'high', 'high', 'low', 'healthy'), 'deficient'),
    (('high', 'high', 'low', 'high', 'high', 'healthy', 'low'), 'deficient'),
    (('high', 'high', 'low', 'high', 'high', 'healthy', 'healthy'), 'deficient'),
    (('high', 'high', 'healthy', 'low', 'low', 'low', 'low'), 'deficient'),
    (('high', 'high', 'healthy', 'low', 'low', 'low', 'healthy'), 'deficient'),
    (('high', 'high', 'healthy', 'low', 'low', 'healthy', 'low'), 'deficient'),
    (('high', 'high', 'healthy', 'low', 'low', 'healthy', 'healthy'), 'average'),
    (('high', 'high', 'healthy', 'low', 'healthy', 'low', 'low'), 'average'),
    (('high', 'high', 'healthy', 'low', 'healthy', 'low', 'healthy'), 'average'),
    (('high', 'high', 'healthy', 'low', 'healthy', 'healthy', 'low'), 'average'),
    (('high', 'high', 'healthy', 'low', 'healthy', 'healthy', 'healthy'), 'average'),
    (('high', 'high', 'healthy', 'low', 'high', 'low', 'low'), 'deficient'),
    (('high', 'high', 'healthy', 'low', 'high', 'low', 'healthy'), 'deficient'),
    (('high', 'high', 'healthy', 'low', 'high', 'healthy', 'low'), 'deficient'),
    (('high', 'high', 'healthy', 'low', 'high', 'healthy', 'healthy'), 'average'),
    (('high', 'high', 'healthy', 'healthy', 'low', 'low', 'low'), 'deficient'),
    (('high', 'high', 'healthy', 'healthy', 'low', 'low', 'healthy'), 'deficient'),
    (('high', 'high', 'healthy', 'healthy', 'low', 'healthy', 'low'), 'average'),
    (('high', 'high', 'healthy', 'healthy', 'low', 'healthy', 'healthy'), 'average'),
    (('high', 'high', 'healthy', 'healthy', 'healthy', 'low', 'low'), 'average'),
    (('high', 'high', 'healthy', 'healthy', 'healthy', 'low', 'healthy'), 'average'),
    (('high', 'high', 'healthy', 'healthy', 'healthy', 'healthy', 'low'), 'average'),
    (('high', 'high', 'healthy', 'healthy', 'healthy', 'healthy', 'healthy'), 'average'),
    (('high', 'high', 'healthy', 'healthy', 'high', 'low', 'low'), 'deficient'),
    (('high', 'high', 'healthy', 'healthy', 'high', 'low', 'healthy'), 'deficient'),
    (('high', 'high', 'healthy', 'healthy', 'high', 'healthy', 'low'), 'average'),
    (('high', 'high', 'healthy', 'healthy', 'high', 'healthy', 'healthy'), 'average'),
    (('high', 'high', 'healthy', 'high', 'low', 'low', 'low'), 'deficient'),
    (('high', 'high', 'healthy', 'high', 'low', 'low', 'healthy'), 'deficient'),
    (('high', 'high', 'healthy', 'high', 'low', 'healthy', 'low'), 'deficient'),
    (('high', 'high', 'healthy', 'high', 'low', 'healthy', 'healthy'), 'average'),
    (('high', 'high', 'healthy', 'high', 'healthy', 'low', 'low'), 'average'),
    (('high', 'high', 'healthy', 'high', 'healthy', 'low', 'healthy'), 'average'),
    (('high', 'high', 'healthy', 'high', 'healthy', 'healthy', 'low'), 'average'),
    (('high', 'high', 'healthy', 'high', 'healthy', 'healthy', 'healthy'), 'average'),
    (('high', 'high', 'healthy', 'high', 'high', 'low', 'low'), 'deficient'),
    (('high', 'high', 'healthy', 'high', 'high', 'low', 'healthy'), 'deficient'),
    (('high', 'high', 'healthy', 'high', 'high', 'healthy', 'low'), 'deficient'),
    (('high', 'high', 'healthy', 'high', 'high', 'healthy', 'healthy'), 'average'),
    (('high', 'high', 'high', 'low', 'low', 'low', 'low'), 'deficient'),
    (('high', 'high', 'high', 'low', 'low', 'low', 'healthy'), 'deficient'),
    (('high', 'high', 'high', 'low', 'low', 'healthy', 'low'), 'deficient'),
    (('high', 'high', 'high', 'low', 'low', 'healthy', 'healthy'), 'deficient'),
    (('high', 'high', 'high', 'low', 'healthy', 'low', 'low'), 'deficient'),
    (('high', 'high', 'high', 'low', 'healthy', 'low', 'healthy'), 'deficient'),
    (('high', 'high', 'high', 'low', 'healthy', 'healthy', 'low'), 'deficient'),
    (('high', 'high', 'high', 'low', 'healthy', 'healthy', 'healthy'), 'average'),
    (('high', 'high', 'high', 'low', 'high', 'low', 'low'), 'deficient'),
    (('high', 'high', 'high', 'low', 'high', 'low', 'healthy'), 'deficient'),
    (('high', 'high', 'high', 'low', 'high', 'healthy', 'low'), 'deficient'),
    (('high', 'high', 'high', 'low', 'high', 'healthy', 'healthy'), 'deficient'),
    (('high', 'high', 'high', 'healthy', 'low', 'low', 'low'), 'deficient'),
    (('high', 'high', 'high', 'healthy', 'low', 'low', 'healthy'), 'deficient'),
    (('high', 'high', 'high', 'healthy', 'low', 'healthy', 'low'), 'deficient'),
    (('high', 'high', 'high', 'healthy', 'low', 'healthy', 'healthy'), 'deficient'),
    (('high', 'high', 'high', 'healthy', 'healthy', 'low', 'low'), 'deficient'),
    (('high', 'high', 'high', 'healthy', 'healthy', 'low', 'healthy'), 'deficient'),
    (('high', 'high', 'high', 'healthy', 'healthy', 'healthy', 'low'), 'average'),
    (('high', 'high', 'high', 'healthy', 'healthy', 'healthy', 'healthy'), 'average'),
    (('high', 'high', 'high', 'healthy', 'high', 'low', 'low'), 'deficient'),
    (('high', 'high', 'high', 'healthy', 'high', 'low', 'healthy'), 'deficient'),
    (('high', 'high', 'high', 'healthy', 'high', 'healthy', 'low'), 'deficient'),
    (('high', 'high', 'high', 'healthy', 'high', 'healthy', 'healthy'), 'deficient'),
    (('high', 'high', 'high', 'high', 'low', 'low', 'low'), 'deficient'),
    (('high', 'high', 'high', 'high', 'low', 'low', 'healthy'), 'deficient'),
    (('high', 'high', 'high', 'high', 'low', 'healthy', 'low'), 'deficient'),
    (('high', 'high', 'high', 'high', 'low', 'healthy', 'healthy'), 'deficient'),
    (('high', 'high', 'high', 'high', 'healthy', 'low', 'low'), 'deficient'),
    (('high', 'high', 'high', 'high', 'healthy', 'low', 'healthy'), 'deficient'),
    (('high', 'high', 'high', 'high', 'healthy', 'healthy', 'low'), 'deficient'),
    (('high', 'high', 'high', 'high', 'healthy', 'healthy', 'healthy'), 'average'),
    (('high', 'high', 'high', 'high', 'high', 'low', 'low'), 'deficient'),
    (('high', 'high', 'high', 'high', 'high', 'low', 'healthy'), 'deficient'),
    (('high', 'high', 'high', 'high', 'high', 'healthy', 'low'), 'deficient'),
    (('high', 'high', 'high', 'high', 'high', 'healthy', 'healthy'), 'deficient'),

]

